### ISSUE TITLE
'error while reading input coordinates' while doing QCG

### ISSUE THREAD

**Issue by in-dec** [crest-lab/crest#100]
I'm trying to use QCG to calculation the solvation free energies, and trying to run the example provided in the docs. I copied the 'pentanol.xyz' and 'benzene.coord' files and used the same command to run the QCG. However, it shows the 'error while reading input coordinates' and the crest.out file stops at solute cluster generation step.

**Comment by in-dec** [comment]
> 

Thanks! However, after installing xtbiff, the other issue occurs that "FATAL: kernel too old". If there any chance to compile a xtbiff in old kernel version? For xib, I can only use xtb-210201-oldkernel.

**Comment by cplett** [comment]
Unfortunately,  this is currently not possible. But there is work in progress to include the features of xtbiff in the xtb program so that xtbiff will soon not be required anymore for the QCG.

**Comment by in-dec** [comment]
> 

I'm also trying to compile xtbiff by myself, while I cannot find source code in the xtbiff release page. The two zipped files there only contain a readme.md file inside. So, is there any chance to provide the source code of xtbiff to be compiled by ourselves. Thansk!

**Comment by awvwgk** [comment]
The `xtbiff` project is currently not open source mainly because it builds on a fork of `xtb` 5. Christoph @cplett is working on upstreaming the `xtbiff` into the `xtb` main branch, until this is done we won't provide the source code for `xtbiff`.

Regarding the old kernel versions, I usually compile (or forget to compile) those variants of `xtb`. We only have a few machines left with a setup suitable for compiling `xtb` and not being updated for quite some time.

**Comment by in-dec** [comment]
> 

Is there any chance to provide a compiled xtbiff in old kernel? Currently, we cannot upgrade our HPC system; so that I failed to run crest as well as xtbiff on our HPC.

**Comment by awvwgk** [comment]
No promises, though. Keep in mind that Linux 2.6 reached it EOL in 2016, while our binaries are Linux 3.0 upwards compatible.

Christoph, in case you are interested in looking into this. The only queue running Linux 2.6 is _hedy_ on _marie_ and only the machine _hedy20_ installs the development libraries for linking statically. The node is currently occupied and I'm not launching compilers on nodes where people run computations.
