### ISSUE TITLE
Diazines cis/trans isomerisation

### ISSUE THREAD

**Issue by fiszczyp** [crest-lab/crest#108]
Hi,

I'm using CREST 2.11.2 with xtb 6.4.1. For some diazines I'm looking into, there seems to be cis/trans isomerisation occurring during CREST conformational search. The problem occurs with both GFN-FF and GFN2-xTB, while with GFN1-xTB I seem to be only getting trans diazines, which is the input isomer (could be just due to the particular one structure I tried it on). I tried both versions 3 and 4 of the CREST algorithms, as well as constraining all bonds (which I believe only deals with bond lengths, not isomers?) and with no Z-matrix crossing.

I can manually filter the structures that do not correspond to the initial SMILES (e.g., using xyz2mol, https://github.com/jensengroup/xyz2mol) but it could be useful to have a check like that done when generating new structures in the algorithm?

Example structure:
[xtbopt.txt](https://github.com/grimme-lab/crest/files/8324975/xtbopt.txt)

Sample outputs (GFN2 and GFN1):
[crest_conformers_gfn1.txt](https://github.com/grimme-lab/crest/files/8325020/crest_conformers_gfn1.txt)
[crest_conformers_gfn2.txt](https://github.com/grimme-lab/crest/files/8325021/crest_conformers_gfn2.txt)

**Comment by pprcht** [comment]
This is probably due to a (relatively) low torsion barrier of the diazo group in GFN-FF and GFN2.
I could probably adapt the topology check we use for cis/trans carbon-carbon bonds also for the diazine case, but I'll have to look into that.
If GFN1 seems to be working, please use that for the meantime.
