### ISSUE TITLE
Adopt same IO library as xtb?

### ISSUE THREAD

**Issue by awvwgk** [crest-lab/crest#111]
I just transitioned `xtb` to to use the geometry file readers / writers from [`mctc-lib`](https://github.com/grimme-lab/mctc-lib). Getting `crest` to use the same IO library would ensure files written by `xtb` can be read by `crest` and vice versa as round-tripping coordinates is extensively tested with this library. Also, it would allow to easily add support for new geometry formats in `crest` (QChem, PDB, SDF/V3000, QCSchema JSON, ...).

In `xtb` the library was implemented by changing the reader routine to

- become a thin wrapper around the `read_structure` procedure:
  https://github.com/grimme-lab/xtb/blob/76c6af2b868996080c050b6ad4e06083d5be1c15/src/io/reader.f90#L63-L68
- error on features supported in the library but blocked / not supported in `xtb`
- overload assignment between `structure_type` from the library and `TMolecule` from `xtb`
  https://github.com/grimme-lab/xtb/blob/76c6af2b868996080c050b6ad4e06083d5be1c15/src/type/molecule.f90#L376-L396

**Comment by pprcht** [comment]
Yeah sure, I'm open to that.
Let's discuss in private what would be best for an integration.
