### ISSUE TITLE
forrtl: servere (24): end-of-file during read, unit -XXX, file /url/...../qcg_tmp/tmp_grow/xtbscreen.xyz

### ISSUE THREAD

**Issue by liyunlutest** [crest-lab/crest#114]
when I run the crest --qcg function, (crest-2.11.2, xtb-6.4.1), this error alwaps pop up. When looking for the xtbscreen.xyz file, the energy of the final structure always appears as an asterisk instead of a number. This is probably the wrong reason. Is this a bug or how to fix it?
![1](https://user-images.githubusercontent.com/105147986/167288262-1a25441d-fbd2-4fac-a3bc-3c3b34d39fdf.jpg)
![2](https://user-images.githubusercontent.com/105147986/167288265-8b28d0cc-4e34-40b3-860a-f960fcc79c74.jpg)

**Comment by cplett** [comment]
Hi,
I noticed that QCG had a bug regarding the wall potentials that only applied for CO2 as a solute. Thanks for pointing this out. I've uploaded a version with a bug fix that should hopefully solve your problem.

**Comment by hpatel1567** [comment]
Hi! I am getting a similar error at similar time (right after size 5) although the xtbscreen.xyz file doesnt have asterisk. 


commnad: `crest /global/home/groups/lr_mp/hpatel/xtb/mols/li.xyz --qcg /global/home/groups/lr_mp/hpatel/xtb/mols/h2o.xyz --nsolv 20 --alpb water --chrg 1 --gsolv --T 8 --nopreopt -nocross
`
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/54923231/208006947-17fdcca4-a4dd-49b7-bdb4-c8b982458858.png">

**Comment by cplett** [comment]
Hi,
This seems to be a problem with the `xtbiff` output. It appears that the top line of the `xtbscreen.xyz` shows `--` instead of `16` which probably caused the error. 
Might I ask, which crest version you use and if the problem occurs every time you perform this calculation?
If you have the possibility to compile the source code of crest and `xtb`, you might try to use `xtb` and crest versions compiled from the newest source code. With this, `xtbiff` is replaced by the improved aISS algorithm in `xtb` which is less prone to errors.

**Comment by hpatel1567** [comment]
Hi, the xtbscreen.xyz file looks fine, there is no --, at the top first line its 16 just cut during screen shot. im using crest 2.12 and it occurs everytime i run this or other calc. Im having a lot of issues compiling from source on my system, so wondering if there is an easy fix to this. Thanks!

**Comment by cplett** [comment]
Sorry, I didn't notice that it was just cropped. Another possible explanation is that the xtbiff didn't converge properly and that the `xtbscreen.xyz` is from the previous step and was not deleted. Could you please check the `iff.out` file if the calculation went well?
Moreover, this seems to happen if the wall potential is too small which should automatically be adjusted. This seems to fail in your calculation, but a possible way to fix this would be to set the wall potential directly from the start to a higher value, _e.g._, `--wscal 0.9`.
