### ISSUE TITLE
Ensemble generation for charged complexes qcg

### ISSUE THREAD

**Issue by froze-jameel** [crest-lab/crest#128]
Hello, i have been trying to generate ensemble using a charged molecule as solute and acetonitrile as solvent using crest QCG. However in the resulted QCG structures i see that the solvent interacts with the solute thus, protonating the solute. What i would like to ask that, if there exist a way where to generate an solute solvent ensemble for charged complexes with the solvent protonating or de-protonating the solute species.
Thanks

**Comment by cplett** [comment]
Hi,
currently, there is possibility to define protonation states in QCG. But if you want a certain protonation state that is not favored by our GFN methods, you might add your solute with one added solvent molecule in the protonation state you desire as input for the solute and constrain this geometry by using, for example, the "--fixsolute" to keep your protonation state.
