### ISSUE TITLE
GFN0 with crest?

### ISSUE THREAD

**Issue by corinwagen** [crest-lab/crest#136]
This is a feature request. 

Based on [the documentation](https://xtb-docs.readthedocs.io/en/latest/crestcmd.html) it appears you can use ``--gfn1``, ``--gfn2``, or ``-gfnff`` to select usage of GFN1, GFN2, or GFNFF methods from ``xtb``. Would it be possible to add support for GFN0 for cases where a higher level of accuracy than GFNFF is desired but GFN2 is too slow? 

best,
Corin

**Comment by pprcht** [comment]
Sure, `--gfn0` exists, but keep in mind that GFN-FF often has comparable accuracy to GFN0 and is of course faster.

**Comment by corinwagen** [comment]
That's fair enough! Didn't realize ``--gfn0`` was an option, thanks for clarifying. Thanks for all your work on this program.
