### ISSUE TITLE
run crest at least twice?

### ISSUE THREAD

**Issue by jouteurestaque** [crest-lab/crest#137]
HI
in the paper 2019 paper, it is (10.1021/acs.jctc.9b00143) quoted ref 9 and its supporting info in order to apprehend the fact that it is better to run CREST at least twice .
But nothing is said about that in that 2017 paper supporting.
what do we do with those CRESTs
do we merge them, and cregen then?

thank you.

**Comment by pprcht** [comment]
Hi,
I'm not exactly sure what the 2019 and 2017 paper are referring to, but you should be able to merge two (or more) `crest_conformers.xyz` files into one if the atom order in both is the same and run cregen on it. You can then proceed with the output `crest_ensemble.xyz`

**Comment by jouteurestaque** [comment]
thanks Philipp
ok this is what I do, still playing on the edge with cregen. thanks
