### ISSUE TITLE
Segmentation error

### ISSUE THREAD

**Issue by andre-cloud** [crest-lab/crest#138]
I'm currently having strange behavior with crest 2.12. With other jobs, the software ends its routine correctly, but with a single file, it throws a segmentation error. 

```
     ========================================
     |        Structure Crossing (GC)       |
     ========================================
 =============================
  # threads =           4
 =============================
 input  file name : crest_rotamers_3.xyz
number of atoms                :    49
number of points on xyz files  :   403
conformer energy window  /kcal :    6.00
CN per atom difference cut-off :  0.3000
RMSD threshold                 :  0.2500
max. # of generated structures : 400
 reading xyz file ...
 # in E window                403
 generating pairs ...       81405

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x105783f17
#1  0x105782f63
#2  0x1929bf4a3
#3  0x104f0d32f
[1]    22703 segmentation fault  crest qa.xyz -g toluene -T 4
```

I attach the xyz file, which was generated from previous xtb optimisation. 

[qa.xyz](https://github.com/crest-lab/crest/files/9506660/qa.log)

I tried on differents machine and on different OSs, but the same error popped out.

**Comment by pprcht** [comment]
Hi,
The crossing routine is a bit prone to such errors, could also be related to #109 
The error code you get seems to be from a gfortran build, have you tried an ifort one?
The easiest way to avoid the error for this system is running the calculation with `-nocross`

**Comment by andre-cloud** [comment]
Are the results comparable with the ones generated with the ```--cross``` algorithm?

**Comment by pprcht** [comment]
Yes, for molecules this small new conformers will only very rarely be generated by the crossing. The crossing was intended for rotamers, mostly.

**Comment by andre-cloud** [comment]
I'll surely try it out

Thanks so much
