### ISSUE TITLE
restarting stopped crest job? 

### ISSUE THREAD

**Issue by corinwagen** [crest-lab/crest#14]
Hello,

I'm running ``crest`` on a large and rather flexible system, and although I'm close to finishing after 7 days the cluster automatically kills my job. Is there any way I can restart ``crest`` from where I left off? If I just rerun the script in the same working directory, will it delete all my old data? 

Thanks,
Corin

**Comment by pprcht** [comment]
That's currently not possible. Starting a job in the same directory will overwrite files, so you probably should not do that if you want use the `crest_conformers.xyz` file that has been produced up to the stop. 

For very large/flexible molecules running `crest` with GFN-FF (`--gfnff`) will speed things up quite a bit. Maybe your job will finish in under 7 days then.

I will look into a restart option, we have been asked for this multiple times now.

**Comment by asmusod** [comment]
Hi @pprcht , 

I unfortunately ran out of memory right at the start of the GC step, would it be possible to start from there (on another machine with more memory)?

**Comment by pprcht** [comment]
Hi,
your best bet is to re-sort the latest `crest_rotamers_` file with the `--cregen` option. After the GC step there isn't much done any more and the file probably contains already a good ensemble. This can of course be done on another machine.
There is still no dedicated re-start option.

**Comment by asmusod** [comment]
Thanks for the tip!
