### ISSUE TITLE
cluster grow - nanoparticle

### ISSUE THREAD

**Issue by matteo-northvolt** [crest-lab/crest#146]
Hey, thanks for making this repository available! I was wondering if there is a way to use the qcg to grow a nanoparticle, e.g., by using a single atom instead of a solvent molecule.

**Comment by cplett** [comment]
Hi,
In principle, this should be possible, but I have never tried it. Probably, it will be a good idea to loosen the wall potential with the "--wscal" command, depending on the size of the nanoparticle you want to generate.
