### ISSUE TITLE
QCG: documentation of output columns

### ISSUE THREAD

**Issue by rkingsbury** [crest-lab/crest#150]
Hello, is there somewhere I can find a description of the columns in the GROW stage of the algorithm?

The first several columns are relatively self-explanatory, but it's not clear to me:
- What are the units of Density?
- What is the meaning of Efix, R, av/act., and Surface?

Thank you!

```bash
=========================================
  |   quantum cluster growth: GROW        |
  =========================================


  Water as solvent recognized, adjusting scaling factor for outer wall pot to 0.70

  Constraining solute during Growth 
 Solute:
       unit ellipsoid axis a,b,c     :   0.333   0.333   0.333
 Solvent:
       unit ellipsoid axis a,b,c     :   0.387   0.322   0.292

  solvent anisotropy            :     1.133
  solute anisotropy             :     1.000
  roff inner wall               :     0.491
  solute max dist               :     0.000
  solvent max dist              :     7.286
  inner unit axis               :     0.333     0.333     0.333
  inner ellipsoid/Bohr          :     5.385     5.385     5.385
  scaling factor outer ellipsoid:     0.700
  outer ellipsoid/Bohr          :     6.615     6.615     6.615

  Size  E /Eh       De/kcal   Detot/kcal  Density   Efix         R   av/act. Surface   Opt
    1    -4.976112  -44.89     -44.89       0.458     -2.488      0.0   0.0     610.1   normal
    2   -10.102633  -35.13     -80.01       0.656     -3.818      3.5   3.5     733.8   normal
    3   -15.216198  -27.00    -107.01       0.790     -4.812      3.6   3.6     865.0   normal
    4   -20.319582  -20.61    -127.62       0.881     -5.636      3.7   3.7    1005.3   normal
```

**Comment by cplett** [comment]
Hi,
Thank you for pointing out, that an explanation of the columns is missing. I will probably add an explanation in a few days.
For clarification:

- The unit of the density should be u/Å^3.

- Efix is the total energy of the cluster divided by the square root of the number of atoms within the cluster.
- Surface is actually the cluster volume in bohr^3 (the declaration went wrong).
- av/act. is the difference in distance between the center of mass of the last added solvent and the solute.
- R is the mean difference of the center of mass between all solvents (excluding the last added one) and the solute.

av/act. and R can give hints, if the next solvent shell is occupied, which is seen in an increase of av/act..

**Comment by rkingsbury** [comment]
Thank you very much!

How is the cluster volume calculated? From an isodensity surface, or from a superposition of atomic radii (e.g. VdW radii)?

Also can you please elaborate on
>av/act. and R can give hints, if the next solvent shell is occupied, which is seen in an increase of av/act..

I suppose the  solvents in a single shell should all have similar av/act values, and then when one places a solvent in the NEXT shell, there should be a step change in av/act?

**Comment by cplett** [comment]
The cluster volume is calculated via surface integrals.
>I suppose the solvents in a single shell should all have similar av/act values, and then when one places a solvent in the NEXT shell, there should be a step change in av/act?
That is correct. In one solvent shell, every molecule should have a similar R value. Placing a solvent molecule in the next shell leads to a higher value as the distance to the solute increases.
