### ISSUE TITLE
QCG: .xcontrol Error

### ISSUE THREAD

**Issue by Olleyboy1** [crest-lab/crest#152]
Hello, While attempting the constraining the solute example for QCG it came up with an error: 

error while reading input coordinates

All the other examples work fine and even the same example without the .xcontrol file works. How do I go about fixing/correcting this?
[Crest.out.txt](https://github.com/crest-lab/crest/files/9951645/Crest.out.txt)

**Comment by cplett** [comment]
Hi,
Could you please provide me with the solute, solvent, and xcontrol file, so that I can check on that?

**Comment by Olleyboy1** [comment]
Please find the requested files attached
[solute.xyz.txt](https://github.com/crest-lab/crest/files/9951710/solute.xyz.txt)
[solvent.xyz.txt](https://github.com/crest-lab/crest/files/9951711/solvent.xyz.txt)
[xcontrol.txt](https://github.com/crest-lab/crest/files/9951714/xcontrol.txt)

**Comment by cplett** [comment]
Thank you very much. This seems to be a bug in the aISS algorithm in `xtb`. I will try to provide a fix for that as soon as possible.

**Comment by Olleyboy1** [comment]
Thank you for sorting it out so quickly

**Comment by cplett** [comment]
Hi,
I've uploaded a bugfix for the `xtb` source code, which is already merged into the main branch of `xtb`. With this update, your calculation should run as expected. Thank you again for pointing this out.

**Comment by Olleyboy1** [comment]
Hi,
Thanks for resolving the issue
