### ISSUE TITLE
Fix atoms in conformation search does not work

### ISSUE THREAD

**Issue by AssoliLan** [crest-lab/crest#156]
Hi,

  I tried to do a conformation search on top of the example https://xtb-docs.readthedocs.io/en/latest/crestxmpl.html#conformers-metal-organic
  , while fixing a couple of atoms. But in comparing crest_best.xyz, looks like the distances between fixed atoms have been changed.

  Let me use a simplified example
```
$coord
       -5.21599553536500        0.00000000000000        0.00000000000000      h
       -3.32626941073900        0.00000000000000        0.00000000000000      h
       -1.47872928122117        0.00000000000000        0.00000000000000      f
$end
```

(The HH distance is 1 angstrom)
with `.xcontrol`
```
$fix
   atoms: 1, 2
   reference=coord
$end
```
and I run `crest coord -g water -xcontrol  -ewin 6 -T 1  -chrg 1 -nci --noreftopo`
I got `crest.best`
```
  3
         -5.25512302
 H         -1.6999947415       -0.0696963457       -0.0000000017
 H          1.0307752574       -0.1215324863       -0.0000000027
 F          0.0355033223        0.0101450406        0.000000000
```
The HH distance is > 2 angstrom. If this is right, how to let atoms fixed?

**Comment by AssoliLan** [comment]
Thanks. I tried four attempts. None of them kept the `HH` distance fixed.
(1) change `.xcontrol` as
```
$fix
   atoms: 1, 2
   reference=input.xyz
$end
```
and use
`crest input.xyz -g water -xcontrol -ewin 6 -T 1 -chrg 1 -nci --noreftopo`
the `crest_best.xyz` is
```
  3
         -5.23571643
 H         -3.8794142426        0.0525295860        0.0000000004
 H          1.0497545142        0.2352837427        0.0000000019
 F          0.1501186437       -0.0152690255       -0.0000000001
```
(2) 
`crest coord -g water -xcontrol -ewin 6 -T 1 -chrg 1 -nci --noreftopo`
the `coord` is conerted from `input.xyz` (ang to bohr)
it leads to
```
 ------------------------------------------------
 Optimizing all 1 structures from file "crest_rotamers_1.xyz" ...
 1
 done.
 running RMSDs...
 done.
 E lowest :     1.00000
forrtl: severe (24): end-of-file during read, unit -2455, file /.../crest_rotamers_3.xy
```

(3) by `crest input.xyz -g water -ewin 6 -T 1 -chrg 1 -nci --noreftopo --cinp constraints.inp`
which `constraints.inp` is
```
$fix
   atoms: 1, 2
   reference=input.xyz
$end
```
the `crest_best.xyz` is
```
  3
         -5.29258193
 H         -1.1839459219       -0.0047358393       -0.0000000472
 H          1.1775039365       -0.0047645057       -0.0000000472
 F          0.0003417592        0.0005040107        0.0000000050
```

(4) by `crest coord -g water -ewin 6 -T 1 -chrg 1 -nci --noreftopo --cinp constraints.inp`
it leads to
```
-----------------------
Multilevel Optimization
-----------------------

 -------------------------
 1. crude pre-optimization
 -------------------------
 running RMSDs...
 done.
 E lowest :************
forrtl: severe (24): end-of-file during read, unit -633, file /.../crest_rotamers_1.xyz
```

**Comment by pprcht** [comment]
Please try the examples as described in https://crest-lab.github.io/crest-docs/page/examples/example_4.html
There are several things that do not add up in you input. For example, avoid the `$fix` keyword and use the `$constrain` syntax instead. *Exact* fixing of atoms with the `$fix` command is not really possible, only applying some strong constraints is.

**Comment by AssoliLan** [comment]
Thanks a lot. https://crest-lab.github.io/crest-docs/page/examples/example_4.html  ` methanol-acetamide complex` example works.

In the system `HHF^+`, if I use 
```
$constrain
   atoms: 1, 2
   force constant = 2.
   reference=input.xyz
$end
``` in `constraints.inp`, and `crest input.xyz -g water -ewin 6 -T 1 -chrg 1 -nci --noreftopo --cinp constraints.inp`  leads to
```
3
         -5.19458649
 H         -1.8378720903        0.0000000000        0.0000000000
 H         -0.8353565096        0.0000000000        0.0000000000
 F          0.1418196851        0.0000000000        0.0000000000
```
it works!  Though if I choose `-T 3`, it leads to 
```

 Trial MTD 1 did not converge!
 Reducing the time step to 4 fs and trying again...

 Trial MTD 2 did not converge!
 Reducing the time step to 3 fs and trying again...

 Trial MTD 3 did not converge!
 Reducing the time step to 2 fs and trying again...

 Trial MTD 4 did not converge!
 Reducing the time step to 1 fs and trying again...

 Trial MTD 5 did not converge!
 Time step can`t be reduced further!
 Trying to turn SHAKE off...

 Trial MTD 6 did not converge!
 Automatic xtb restart failed 6 times!
 Please try other settings by hand.
``` and `force constant = 1.` works for 3 cores with similar HH distance anyway. Seems when the force constant become large, parallelization may have issue,
