### ISSUE TITLE
QCG: Boltzmann averaged energy of final cluster

### ISSUE THREAD

**Issue by alan-arnold** [crest-lab/crest#162]
Looking more closely at the output from one of the test runs mentioned in #160 I've noticed something that I don't understand:

`crest Kr@Q6.xyz --T 24 --qcg h2o.xyz --gsolv --nsolv 10 --alpb h2o --mdlen 1 --nclus 2 --xtbiff -keepdir
`
>   volume filled
>   Starting optimizations + SP  of structures
>   2 jobs to do.
>  
>   done.
> 
>   Cluster   E /Eh        Density  Efix       R   av/act. Surface   Opt
>     1       -50.922259   1.213    0.000     8.4  11.2      690.1   tight
>     2       -50.922524   1.232    0.000     7.9  11.0      631.3   tight
> 
>   ------------------------------------------------------------------------
>   ------------------------------------------------------------------------
>   Boltz. averaged energy of final cluster:
>        G /Eh     :  **-50.92305503** <<<<
>        T*S /kcal :  -0.405
> 
>   Solvent cluster generation finished.
>   Results can be found in solvent_cluster directory
>   Structures in file <crest_ensemble.xyz>
>   Energies in file <cluster_energy.dat> [cluster_energy.dat.txt](https://github.com/crest-lab/crest/files/10290213/cluster_energy.dat.txt)
>   Population in file <population.dat>  [population.dat.txt](https://github.com/crest-lab/crest/files/10290209/population.dat.txt)
> 

This job runs to completion but how can the Boltzmann averaged energy of the final cluster be *lower* than either of the two cluster energies? 

I've just noticed this behaviour in other runs too, eg

>   volume filled
>   Starting optimizations + SP  of structures
>   10 jobs to do.
>  
>   done.
> 
>   Cluster   E /Eh        Density  Efix       R   av/act. Surface   Opt
>     1       -50.918469   1.213    0.000     8.3  10.3      689.3   tight
>     2       -50.917027   1.204    0.000     8.4   8.2      702.6   tight
>     3       -50.920462   1.212    0.000     8.2  11.7      688.3   tight
>     4       -50.918211   1.200    0.000     9.0  11.2      737.2   tight
>     5       -50.920344   1.215    0.000     8.1  11.6      674.4   tight
>     6       -50.921006   1.205    0.000     8.4  11.2      703.9   tight
>     7       -50.916208   1.226    0.000     8.1  11.2      649.3   tight
>     8       -50.920149   1.209    0.000     8.4  10.0      690.9   tight
>     9       -50.918078   1.203    0.000     8.2   9.6      701.4   tight
>    10       -50.919949   1.225    0.000     8.2  11.0      658.8   tight
> 
>   ------------------------------------------------------------------------
>   ------------------------------------------------------------------------
>   Boltz. averaged energy of final cluster:
>        G /Eh     :  **-50.92203528** <<<<
>        T*S /kcal :  -1.039
>

**Comment by cplett** [comment]
Hi,
The `Boltz. averaged energy of final cluster` is the Boltzman-averaged electronic energies plus an entropy term arising from the Gibbs–Shannon equation (equation 9 in the [QCG Paper](https://pubs.acs.org/doi/10.1021/acs.jctc.2c00239)). This additional contribution is also printed out as `T*S /kcal`.
