### ISSUE TITLE
How to avoid chiral axis flipping

### ISSUE THREAD

**Issue by npe1011** [crest-lab/crest#165]
Hello,

When I run conformation search of a molecule involving a chiral axis, e.g. binaphthyl compounds, the result often involves structures in which the chiral axis (R/S) is flipped. Is there any good way to avoid such flipping? 

I currently omit flipped structures manually or by a script, but in the worst case, only flipped structures are found in the result file.

Thank you very much.

**Comment by pprcht** [comment]
Hi,

As there is currently no way to automatically detect the chirality of an atom, I fear that there is no automatic way to prevent that.
However, I assume if you have only a few chirality centers in your structure, you can introduce a dihedral angle constraint on the chiral atom and three of its neighbors to prevent the inversion.
