### ISSUE TITLE
Compilation of Crest-3.0dev

### ISSUE THREAD

**Issue by WentongZhou** [crest-lab/crest#167]
Hi there,

I tried to use cmake and icc ifort to compile the crest 3.0dev following the guidance in the documentation. All configure parts worked well, but the final build step reported errors as below:

CMakeFiles/crest-exe.dir/src/algos/playground.f90.o: In function `crest_playground_':
/home/wz28l/crest-3.0dev/src/algos/playground.f90:124: undefined reference to `better_xyzint_'
/home/wz28l/crest-3.0dev/src/algos/playground.f90:130: undefined reference to `print_zmat_'
/home/wz28l/crest-3.0dev/src/algos/playground.f90:132: undefined reference to `gmetry2_'
/home/wz28l/crest-3.0dev/src/algos/playground.f90:136: undefined reference to `xyzgeo2_'
/home/wz28l/crest-3.0dev/src/algos/playground.f90:137: undefined reference to `print_zmat_'
CMakeFiles/crest-exe.dir/src/rigidconf/tree.f90.o: In function `rigidconf_tree_':
/home/wz28l/crest-3.0dev/src/rigidconf/tree.f90:126: undefined reference to `better_xyzint_'
/home/wz28l/crest-3.0dev/src/rigidconf/tree.f90:128: undefined reference to `print_zmat_'
CMakeFiles/crest-exe.dir/src/rigidconf/reconstruct.f90.o: In function `reconstruct_zmat_to_mol_':
/home/wz28l/crest-3.0dev/src/rigidconf/reconstruct.f90:87: undefined reference to `gmetry2_'

Could you provide some hints about how to solve these problems? Thanks.

Best,
Wentong Zhou

**Comment by pprcht** [comment]
Hi,
I probably forgot to comment these things out after testing them. 3.0dev is a development branch after all.
I pushed a change to the branch, you should now be able to pull and build it.
Tell me if there are further issues.

**Comment by WentongZhou** [comment]
playground.f90 is good now, the tree.f90 still has some issues.

`CMakeFiles/crest-exe.dir/src/rigidconf/tree.f90.o: In function `rigidconf_tree_':
/home/wz28l/crest-3.0dev/src/rigidconf/tree.f90:126: undefined reference to `better_xyzint_'
/home/wz28l/crest-3.0dev/src/rigidconf/tree.f90:128: undefined reference to `print_zmat_'
CMakeFiles/crest-exe.dir/src/rigidconf/analyze.f90.o: In function `prune_zmat_dihedrals_':
/home/wz28l/crest-3.0dev/src/rigidconf/analyze.f90:174: undefined reference to `dihed2_'
CMakeFiles/crest-exe.dir/src/rigidconf/reconstruct.f90.o: In function `reconstruct_zmat_to_mol_':
/home/wz28l/crest-3.0dev/src/rigidconf/reconstruct.f90:87: undefined reference to `gmetry2_'`

**Comment by pprcht** [comment]
Ah, I think I know where the error comes from then.
There was a source file missing form `CMakeLists.txt`. Sorry.

**Comment by WentongZhou** [comment]
It works now. Thanks for your help.

Best,
Wentong
