### ISSUE TITLE
MECP Issue

### ISSUE THREAD

**Issue by abedisyedaliabbas** [crest-lab/crest#172]
Hello,

Whenever I try to run MECP using the following keywords:

crest --input input.toml

It always just do the normal optimization for me and never use the .toml file as user input. Can you please help me figure out the issue?

i just try to reproduce the benzene results from the documentations page and it only gives me a normal conformational search. 
https://crest-lab.github.io/crest-docs/page/examples/mecp/mecp_opt.html

**Comment by pprcht** [comment]
Hi,
the .toml stuff is only present in the development version, so if you are using 2.12 the program doesn't know anything about it. You will need to built the version from the respective source, as mentioned here: https://crest-lab.github.io/crest-docs/page/releases/release_preview.html

**Comment by abedisyedaliabbas** [comment]
I am not able to see the dev version 3.0. 

![Uploading Capture.JPG…]()

**Comment by pprcht** [comment]
Are you looking in the right repository? I had a colleague double-check, it's definitely visible. 
https://github.com/crest-lab/crest/tree/3.0dev

**Comment by ouielba90** [comment]
I have tried this developing version and when I run the MECP example with the input.toml and struc.xyz files, I got this error,

 
 ```
      ==============================================
       |                                            |
       |                 C R E S T                  |
       |                                            |
       |  Conformer-Rotamer Ensemble Sampling Tool  |
       |          based on the GFN methods          |
       |             P.Pracht, S.Grimme             |
       |          Universitaet Bonn, MCTC           |
       ==============================================
       Version 2.11dev, Fri 15. Jan 12:42:14 CEST 2021
  Using the xTB program. Compatible with xTB version 6.3.3
 
   Cite work conducted with this code as

   P. Pracht, F. Bohle, S. Grimme, PCCP, 2020, 22, 7169-7192.

   and  S. Grimme, JCTC, 2019, 15, 2847-2862.
 
   with help from:
   F.Bohle, S.Ehlert, S.Grimme, P.Pracht
 
   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

 Command line input:
 > ./crest --input input.toml

No (valid) input file! exit.
```

What is the problem? Has anyone faced that issue?
