### ISSUE TITLE
Use .pdb for constraint reference

### ISSUE THREAD

**Issue by Mishakolok** [crest-lab/crest#173]
Hello, I have a question: is there any way to use .pdb files as a reference for constraining atoms while using .pdb file as an input geometry?

My input file looks like this:
```
$constrain
  atoms: 1-4,19-24,42-9237
  force constant=0.01
  reference=macro_molecule.pdb
$metadyn
  atoms: 5-18,25-41
$end
```
And my command is
`crest macro_molecule.pdb --subrmsd --gfnff --gbsa h2o --cinp conf.inp`
If I run it as it is I immediately get
```
 <conf.inp> file present.
 content of the constraining file (sorted):
> $constrain
>   atoms: 1-4,19-24,42-9237
>   force constant=0.01
>   reference=macro_molecule.pdb
> $metadyn
>   atoms: 5-18,25-41
 fix file: macro_molecule.pdb
  atoms: 5-18,25-41
     # of atoms considered for RMSDs:31
 
 -------------------------
 xTB Geometry Optimization
 -------------------------
 
  Initial geometry optimization failed!
  Please check your input.
```
And if I use the same .xyz I get no error and Geometry Optimization proceeds (I think). 

The reason why I want to keep the .pdb format is because the topoly generation is much much faster when using it (I think this is because the charges and fragments are already listed in it). When using GFN-FF as a standalone I have no problems with .pdb, while with .xyz I get stuck at the EEQ constraints caclulations stage (probably due to the large number of atoms in my system).

I have a feeling that xtb uses the file listed in reference as a starting point in geometry optimization, but I am not sure. 

Here are the files I used (they contain around 9000 atoms).
[macro_molecule.zip](https://github.com/crest-lab/crest/files/10742211/macro_molecule.zip)

**Comment by pprcht** [comment]
Hi,
I don't really know if xtb accepts .pdb files as reference. crest doesn't do anything with this, it just passes the constraint on to xtb, so you might want to check the xtb manual regarding the `reference=` keyword. As far as I am aware, xtb does not use this file as starting point for the geometry optimization, just as reference for the constraint.

It's probably wise to first try and get a constrained calculation running with xtb, and only then start transferring the input to crest. Topology generation with GFN-FF shouldn't be a bottleneck as crest re-uses the one set up initially for all further calculations. Also, keep in mind that crest writes coord and xyz inputs for xtb, additional information from pdb files might be lost.
