### ISSUE TITLE
QCG: incorrect Overall wall time

### ISSUE THREAD

**Issue by alan-arnold** [crest-lab/crest#174]
Greetings again Christoph.  I've noticed that the Wall Time Summary : Overall wall time seems to be incorrect. 
It is being reported as significantly longer than the actual elapsed job time I've observed from the elapsed time between the creation- and last-modified timestamps of the saved .out files.

The versions of crest and xtb that I have been using are the codes from Dec 24 2022 compiled with v2021.6.0 ifort and icc compilers from the 2022.2.0 Intel oneAPI toolkits, running on Ubuntu 22.04 (mentioned in  #163)

Here are two examples taken from a series of some noble gas/cucurbit[5]uril runs

`crest He.xyz --T 24 --qcg h2o.xyz --gsolv --nsolv 50 --alpb h2o --mdlen 10 --xtbiff -keepdir > He_crest_10_qcg50_5.out &
`

>  Wall Time Summary
>  -----------------
>              test MD wall time :         0h : 0m : 5s
>                  MTD wall time :         0h :11m : 2s
>       multilevel OPT wall time :         0h :24m :44s
>                   MD wall time :         0h : 3m :12s
>                 Grow wall time :         0h :40m :43s
>      Solute-Ensemble wall time :         1h :12m :35s
>                  CFF wall time :         0h : 1m : 9s
>          Frequencies wall time :         0h : 7m : 5s
> Overall wall time  : 2h :42m :48s

The actual elapsed time was 2h 2m (9:52am to 11:54am). 

`crest He@Q5.xyz --T 24 --qcg h2o.xyz --gsolv --nsolv 50 --alpb h2o --mdlen 10 --nofix -keepdir  > He@Q5_crest_10_qcg50_2.out &
`

>  Wall Time Summary
>  -----------------
>              test MD wall time :         0h : 0m : 9s
>                  MTD wall time :         0h :54m :33s
>       multilevel OPT wall time :         2h : 0m :50s
>                   MD wall time :         0h :48m :11s
>                 Grow wall time :         3h :30m : 2s
>      Solute-Ensemble wall time :         6h :46m : 8s
>                  CFF wall time :         0h : 5m :51s
>          Frequencies wall time :         0h :30m :12s
>   Overall wall time  : 14h :42m :14s	

The actual elapsed time was 10h 52m (7:46am to 6:38 pm)

The Grow and Frequencies phases seem to be correct (by observation), so I suspect the discrepancy (or at least part of it) might lie in the Solute-Ensemble wall time calculation, which appears to be about two times too long.

This is not a critical issue of course, but thought you might like to know there's a bug hiding somewhere. As you can see I use -keepdir so any/all intermediate files are available if they're of help.

**Comment by cplett** [comment]
Hi Alan,
many thanks for drawing my attention to this problem. The `Solute-Ensemble wall time` was doubly counted.
I provided a fix for this with #176.
