### ISSUE TITLE
QCG: Radon gsolv fails with --xtbiff

### ISSUE THREAD

**Issue by alan-arnold** [crest-lab/crest#175]
A series of jobs, identical to the following, run to completion for He to Xe but the Rn instance fails with "error while reading input coordinates" after the Wall scaling factor reaches 1.00 from the default starting value. 

`crest Rn.xyz --T 24 --qcg h2o.xyz --gsolv --nsolv 10 --alpb h2o --mdlen 5 -xtbiff -keepdir > Rn_crest_5_qcg10_1.out &
`

>   |   quantum cluster growth: GROW        |
>  
>   Water as solvent recognized, adjusting scaling factor for outer wall pot to 0.70
>  
>   Constraining solute during Growth 
>  Solute:
>        unit ellipsoid axis a,b,c     :   0.333   0.333   0.333
>  Solvent:
>        unit ellipsoid axis a,b,c     :   0.386   0.322   0.292
>  
>   solvent anisotropy            :     1.133
>   solute anisotropy             :     1.000
>   roff inner wall               :     0.592
>   solute max dist               :     0.000
>   solvent max dist              :     7.284
>   inner unit axis               :     0.333     0.333     0.333
>   inner ellipsoid/Bohr          :     5.803     5.803     5.803
>   scaling factor outer ellipsoid:     0.700
>   outer ellipsoid/Bohr          :     6.876     6.876     6.876
>  
>   Size       E        De       Detot      Density     Eatom    av. R  Rlast   Volume    Opt
>             [Eh]    [kcal]     [kcal]     [u/Å^3]     [kcal]   [bohr] [bohr] [bohr^3]
>    Wall Potential too small, increasing size by 5 %
>    New scaling factor 0.73
>    Wall Potential too small, increasing size by 5 %
>    New scaling factor 0.77
>    Wall Potential too small, increasing size by 5 %
>    New scaling factor 0.81
>    Wall Potential too small, increasing size by 5 %
>    New scaling factor 0.85
>    Wall Potential too small, increasing size by 5 %
>    New scaling factor 0.89
>    Wall Potential too small, increasing size by 5 %
>    New scaling factor 0.94
>    Wall Potential too small, increasing size by 5 %
>    New scaling factor 0.98
>    Wall Potential too small, increasing size by 5 %
>    New scaling factor 1.00
>  <.... output file prematurely stops here ...>

The input structure files are trivial, identical (except for the element) to: [Rn.xyz](https://github.com/crest-lab/crest/files/10753176/Rn.xyz.txt)

Strangely, if --xtbiff is NOT used (defaulting to the aISS method), all jobs for He to Rn run to completion:

`crest Rn.xyz --T 24 --qcg h2o.xyz --gsolv --nsolv 10 --alpb h2o --mdlen 5 -keepdir > Rn_crest_5_qcg10_2.out &`

The versions of crest and xtb that I have been using are the codes from Dec 24 2022 compiled with v2021.6.0 ifort and icc compilers from the 2022.2.0 Intel oneAPI toolkits, running on Ubuntu 22.04 (mentioned in https://github.com/crest-lab/crest/issues/163), and the v1.1 (Sep 27 2017) binary for xtbiff

**Comment by alan-arnold** [comment]
I've done a little more exploration and it appears that this problem lies in xtb-IFF. The last lines of tmp/tmp_grow/iff.out are

>  global optimization in 6D
>  
>  done in fast mode, i.e, without ATM 
>  term but final energies include it.
>  If it should be included use -atm option.
>  ..............................................
>  
> initial Rcma /A    :    0.00
> initial Rmin /A    :    0.06
> R sytem 1          :     NaN
> R sytem 2          :    0.84
> .# of parents       :  100
> .# of generations   :   10
> .# final grad opts  :   15
> R grid step size   :    2.50
> ang step size /deg :   45.00
> .# angular grid size:  512
> include input      : F
> pocket search      : F
> stack search       : T
> angular search     : T
>  
>   generation of start ensemble
>  .
> . # probe R points   :    4913
>

**Comment by cplett** [comment]
Hi,
Thanks for pointing that out. It seems that the `xtbiff` program is missing parameters for Rn. Unfortunately, this is not easily fixable.
However, I'm happy to hear that the `aISS` works for the example. As it performs usually better than the `xtbiff` program, I would anyhow recommend using this.
