### ISSUE TITLE
getting error while doing a conformational analysis of 97 atom molecule in crest with gfn2-xtb

### ISSUE THREAD

**Issue by priyam1720** [crest-lab/crest#180]
getting error while doing a conformational analysis of 97 atom molecule in crest with gfn2-xtb
this is the error what i got in crest.out file
 xTB Geometry Optimization
 -------------------------
 Geometry successfully optimized.
 WARNING! Change in topology detected!
 The topology change was seen in the initial geometry optimization.
 This could be an artifact of the chosen theory level (--gfn2).
 You can check the optimization trajectory in the "xtbopt.log" file.
 Try either of these options:

    A) Pre-optimize your input seperately with xtb and use the optimized
       structure as input for CREST. (Only recommended if structure is intact)

    B) Restart the same CREST call as before, but ignore the topology change
       by using the "--noreftopo" keyword. (May produce artifacts)

    C) Fix the initial input geometry by introducing bond length constraints
       or by using a method with fixed topology (GFN-FF).

and this is the error i got on terminal

ERROR STOP abnormal termination of crest

Error termination. Backtrace:
#0  0x557ca975bde6 in ???
#1  0x557ca984d961 in ???
#2  0x557ca96e6340 in ???
#3  0x1479c756f0b2 in ???
#4  0x557ca96e6370 in ???

this is the xyz file i used for the calculation

96
Energy =
C     1.2894275   -2.2348286    4.8858567
C     3.9982115   -2.3727530    5.6404783
C     1.8922562   -1.1381718    5.5444219
C     2.0513887   -3.3827342    4.6258879
C     3.3965361   -3.4520179    4.9891792
C     3.2435224   -1.2364536    5.9213513
H     3.9654074   -4.3583788    4.7756199
H     3.6942989   -0.3897281    6.4401295
H     5.0472517   -2.4170872    5.9362803
N    -0.0615946   -2.2392045    4.4223090
C    -1.2565733   -2.0294849    5.1314340
C    -0.3764021   -2.7054896    3.1528775
H     0.4104439   -2.9296039    2.4389705
C    -1.7505321   -2.7827967    3.0380457
H    -2.2930729   -3.1000866    2.1520604
C    -2.2997765   -2.3660536    4.2775912
H    -3.3501522   -2.3013677    4.5468219
C    -1.3753645   -1.5515643    6.5380865
C     1.2156185    0.1250523    5.9509710
O    -0.3676039   -0.9490162    7.0627097
O     1.6059663    0.8521000    6.8481103
O    -2.4695026   -1.7519579    7.1263480
H     1.5688513   -4.2379626    4.1513888
N     0.2707025    0.7466853    4.9684449
C     0.4040849    0.5834098    3.6310333
C    -0.6798616    1.6040830    5.4536200
C    -0.3677890    1.2701773    2.7165162
H     1.1593637   -0.1253705    3.2985160
C    -1.4537916    2.3464878    4.6118244
H    -0.7609793    1.6517679    6.5368425
C    -1.2645211    2.2928879    3.1914511
H    -2.1903428    3.0137961    5.0518296
C    -0.0508246   -0.5014371   -1.5098226
C     0.7488033    0.7338534   -1.9690681
C     2.0590616    0.5271434   -2.4212883
C     0.2159671    2.0228988   -2.0266111
C     2.8165774    1.5932787   -2.9055229
H     2.4847358   -0.4762755   -2.3803228
C     0.9840988    3.0879766   -2.5112954
H    -0.8019047    2.2218576   -1.6929419
C     2.2897632    2.8873618   -2.9551289
H     2.8845653    3.7181944   -3.3330643
C    -0.4574428   -1.2653207   -2.7804703
C    -1.1301243   -0.6093072   -3.8173398
C    -0.1687834   -2.6252930   -2.9083000
C    -1.5177261   -1.3110499   -4.9600978
H    -1.3428316    0.4586701   -3.7480458
C    -0.5607936   -3.3174421   -4.0595344
H     0.3630911   -3.1350688   -2.1055170
C    -1.2415846   -2.6740302   -5.0923880
H    -1.5404628   -3.2179765   -5.9871431
O     0.7702078   -1.3640479   -0.7347752
H     1.1105709   -0.7616016   -0.0197700
C    -1.3670660   -0.1605127   -0.7533726
C    -2.3057632   -1.3542176   -0.5430908
H    -1.9156794    0.5871056   -1.3526805
C    -3.3577277   -0.7858024    0.4120007
H    -1.7372371   -2.1789756   -0.0878621
H    -2.7437963   -1.7068113   -1.4838736
C    -2.5786966    0.1787768    1.3218795
H    -4.1220637   -0.2382481   -0.1560969
H    -3.8670603   -1.5616671    0.9970929
H    -3.1107043    1.1314399    1.4520759
H    -2.3878907   -0.2573784    2.3108293
N    -1.2716763    0.3894458    0.6350215
C    -0.1656686    0.8005013    1.2987461
O     1.0039262    0.7282528    0.8542559
C    -1.5279221    3.4621932    0.9887102
C    -2.8174892    4.2043951    2.9234333
C    -2.0065210    4.8996868    0.7775671
H    -2.0682714    2.7714225    0.3227953
H    -0.4472814    3.3313282    0.8381990
C    -3.2462530    4.9772837    1.6764300
H    -2.2849531    4.8552782    3.6356201
H    -3.6535060    3.7181488    3.4443781
H    -1.2356779    5.6075428    1.1157784
H    -2.2226796    5.1016300   -0.2784080
H    -3.5399417    6.0055405    1.9201221
H    -4.1005426    4.4787378    1.1946508
N    -1.8756819    3.1828383    2.3988529
C     0.4053107    4.4791507   -2.4846791
C     4.1991298    1.3305704   -3.4494181
C    -2.2666076   -0.5752011   -6.0420395
C    -0.2394351   -4.7877717   -4.1503824
F    -2.2869221   -1.2537517   -7.2188575
F    -3.5711503   -0.3509200   -5.6911507
F    -1.7205423    0.6509260   -6.2911966
F     1.1016490   -5.0220805   -4.0292531
F    -0.6365306   -5.3430573   -5.3250882
F    -0.8449996   -5.4957793   -3.1489448
F     0.5976578    5.0769098   -1.2658896
F     0.9623015    5.2980929   -3.4136569
F    -0.9423001    4.4770149   -2.7023426
F     4.1566581    0.9454430   -4.7631406
F     4.8378119    0.3350374   -2.7749583
F     4.9967401    2.4316204   -3.3931511

this is the input i give for calculations

 crest input.xyz -gfn2 -T 10 > crest.out &

Please help me out

**Comment by pprcht** [comment]
There was a (chemical) change in topology detected upon optimization of your input, the "error" is simply a early termination of the program because of this.
Have you read the message the program supplies? There are three suggestions it gives you to try.

**Comment by priyam1720** [comment]
I already tried it but the structure is totally changing into a different
structure. there is bond forming and bond breaking happening instead of
conformational analysis

**Comment by pprcht** [comment]
The conformational sampling is *always* tied to a level of theory since a conformer is defined as a minimum on the energy surface. If your system shows chemical changes this is an issue of the underlying theory, i.e., GFN2-xTB in this case, and not necessarily a problem of the sampling.

From your message it seems you tried A) and maybe B), but if chemical changes are occurring and you ***really*** need to avoid bond formation you must either use constraints, or switch to another method that can't do chemical transformations, for example the GFN-FF force field method. Or both. 
At large molecule sizes it is sometimes also helpful to turn on implicit solvation instead of running gas phase calculations.

**Comment by priyam1720** [comment]
Thank you for the clarification.
