### ISSUE TITLE
Protonation/cation site searches as inputs

### ISSUE THREAD

**Issue by Mass-Spec** [crest-lab/crest#182]
Is the output of a protonation sampling job or cation binding site sampling job an appropriate input structure for a conformational search? I am getting topology change errors when doing so and I think this may be the issue. 

 Would it be better to run an xtb optimization on these protonated/cation-bound structures before proceeding with conformational searches?

**Comment by pprcht** [comment]
Hi,
the output of the protonation sampling job should already be optimized at the xtb level. Maybe it is some other setting. Have you set the correct charge?
