### ISSUE TITLE
Is it possible to change the output name for CREST clustering?

### ISSUE THREAD

**Issue by camKD** [crest-lab/crest#184]
The output is always crest_clustered.xyz. I'm wondering if there is a way to change this to something else? I am checking different clustering options/energy thresholds, so it would be good if I could differentiate them in the output file. Apologies if this information is already listed somewhere. All the best!

**Comment by pprcht** [comment]
Hi, do you mean renaming it with `mv` or `cp`? If you are testing different settings, then you are probably calling CREST repeatedly  and could rename the files in between?
