### ISSUE TITLE
Crest uses capital letters for two-letter element symbols in xyz output

### ISSUE THREAD

**Issue by mhrmsn** [crest-lab/crest#19]
More of a suggestion than a real issue: CREST seems to output two-letter element symbols with two capital letters, e.g. "IR" for Iridium instead of "Ir". I'm not aware of a clear specification of the xyz format, but it might make sense to output such element symbols only with one capital character for the crest_*.xyz files.

Some programs will not correctly interpret the all-caps element symbols (e.g. Schrödinger's Maestro), and while others tolerate them, they always output only xyz files with single capital letter element symbols (Avogadro, molden, ChemAxon's molconvert, Turbomole's x2t/t2x).

I also noticed, that in xtb this seems to depend on the input - `xtb mymol.xyz -o` for example seems to preserve the original input with either two or single capital letter element symbols.

**Comment by pprcht** [comment]
I also don't think that the `.xyz` format is clearly defined somewhere.
I'll change the element symbols for the next release.

**Comment by awvwgk** [comment]
There is [a CCL email](http://www.ccl.net/chemistry/resources/messages/1996/10/21.005-dir/index.html) regarding the xyz format (Xmol), specifying that the atomic identifier should be *“a short string of alphanumeric characters”*.
