### ISSUE TITLE
No "thermo_data" folder

### ISSUE THREAD

**Issue by hpatel1567** [crest-lab/crest#194]
Hi

I am using QCG with Jan 2023 bleeding edge version of xtb. I do not see a "thermo_data" folder within the ensemble folder or anywhere else. How do I determine the configurational entropy? I don't see it in the output either. 

Thanks, 
Hetal

**Comment by cplett** [comment]
Hi,
that the `thermo_data` file is missing in the `ensemble` folder is strange and I'm yet unsure how this can happen.
However, there is the possibility to analyze the resulting ensemble( _e.g._ `full_ensemble.xyz` in the `ensemble directory`) with `crest` afterwards. You can use the `cluster.xyz` in the `grow` directory and `cregen` which is invoked with the command line call `crest cluster.xyz --cregen full_ensemble.xyz` to get different information (including the configurational entropy) of the final ensemble.
