### ISSUE TITLE
virtual memory 

### ISSUE THREAD

**Issue by jouteurestaque** [crest-lab/crest#197]
Hi guys

I have a virtual memory problem for the first time ever with crest Version 2.12,

forrtl: severe (41): insufficient virtual memory
Image              PC                Routine            Line        Source             
crest              000000000151947B  Unknown               Unknown  Unknown
crest              000000000048068B  confcross_                121  confcross.f90
crest              000000000067BF57  cross2_                   902  confscript2_misc.f90
crest              000000000066F129  confscript2i_             249  confscript2_main.f90
crest              00000000006984BE  MAIN__                    276  crest_main.f90
crest              0000000000402242  Unknown               Unknown  Unknown
crest              00000000017025D0  Unknown               Unknown  Unknown
crest              000000000040210E  Unknown               Unknown  Unknown

it is crashing at the 
========================================
     |        Structure Crossing (GC)       |
     ========================================
 input  file name : crest_rotamers_4.xyz
number of atoms                :    52
number of points on xyz files  : 25690
conformer energy window  /kcal :    6.00
CN per atom difference cut-off :  0.3000
RMSD threshold                 :  0.2500
max. # of generated structures : 3450

if I relaunched it with --nocross
it is ok but it resulted in an impressive number of conformers, pretty annoying to follow up with CENSO

any other way do managed that?

it was an 
`xtb xtbopt_LA_rotation.xyz --opt --gfn2 -alpb water`

`52

C          0.87883        0.21307        0.97715
C          0.27223        0.72110       -0.33394
C         -1.23922        0.51386       -0.38987
C         -1.83069        1.03293       -1.69897
C         -3.34495        0.84292       -1.75550
C         -3.95328        1.22590       -3.10436
C         -3.86225        2.73408       -3.38598
C         -4.51295        3.01947       -4.70968
O         -3.96206        2.92725       -5.78713
O         -5.78803        3.35415       -4.58980
C          2.35152        0.47624        1.01798
C          3.32992       -0.38321        1.25721
C          3.20950       -1.83935        1.60408
C          3.88535       -2.08774        2.92323
C          3.30082       -2.19208        4.10694
C          1.83610       -2.12820        4.40572
C          1.30908       -3.49344        4.86182
C         -0.16800       -3.43790        5.24279
C         -0.69062       -4.79329        5.71414
C         -2.16217       -4.72921        6.10653
H          0.66454       -0.85002        1.08305
H          0.40408        0.73731        1.81242
H          0.74226        0.19782       -1.16992
H          0.49473        1.78508       -0.44394
H         -1.70646        1.03410        0.44937
H         -1.46355       -0.55019       -0.28639
H         -1.58495        2.09134       -1.79830
H         -1.36943        0.50432       -2.53641
H         -3.81536        1.43178       -0.96595
H         -3.57328       -0.20813       -1.56660
H         -5.00531        0.93330       -3.11531
H         -3.44371        0.68557       -3.90510
H         -2.81867        3.03906       -3.44008
H         -4.38319        3.28745       -2.60615
H         -6.06336        3.48040       -3.66071
H          2.61522        1.50506        0.80274
H          4.35171       -0.02370        1.23754
H          3.72291       -2.42454        0.83543
H          2.16923       -2.15320        1.63461
H          4.96559       -2.14176        2.87027
H          3.92297       -2.36813        4.97636
H          1.67587       -1.40371        5.20877
H          1.27424       -1.78887        3.53647
H          1.89201       -3.83492        5.72056
H          1.45254       -4.21882        4.05745
H         -0.75219       -3.10616        4.38129
H         -0.30722       -2.70277        6.03910
H         -0.55858       -5.52766        4.91631
H         -0.10117       -5.12763        6.57094
H         -2.76870       -4.41665        5.25961
H         -2.30943       -4.01603        6.91444
H         -2.51197       -5.70318        6.43964

thank you for any help`

**Comment by pprcht** [comment]
Hi,
this is the same problem you will find on a couple of crossing related issues.
I'm working on a fix on the  3.0dev development branch, but have to adjust it for better performance. Maybe I get to it over the weekend.

The current workaround is the `--nocross` that you already used. 
However, even fixing it won't reduce the number of conformers. On the contrary, you will end up with even more of them...
I took a look at your system as well; The huge number of conformers shouldn't surprise you, it doesn't get much more flexible than such a linear molecule.

**Comment by jouteurestaque** [comment]
right sure about the linear molecule.
I was surprised of that number cause the same one with one added double bond managed to crest it over giving  4692 conformers while this one resulted in 13549 conformers (with the nocross then)...
Thank you again Philipp

**Comment by pprcht** [comment]
Hm, so the same molecule but with one less degree of freedom managed to get "only" 4692 structures, do I understand that right? Sounds plausible to me as the additional C-C torsion would add a factor of ~3 more conformers

**Comment by jouteurestaque** [comment]
yes that molecule
50
 energy: -61.935060706640 gnorm: 0.000287960008 xtb: 6.4.1 (afa7bdf)
C         0.31303053771271    0.12336060879078    0.46490562023108
C         0.17524145857475   -0.96637805776786    1.52597304584380
C        -0.74685386296152   -0.57230889714948    2.68079902959298
C        -2.19411918700789   -0.27171250478590    2.28186704184839
C        -2.91184986888834   -1.40416659375279    1.54550104223409
C        -3.02207093487078   -2.67946910680251    2.37731828599242
C        -3.87866211568206   -3.73488554422483    1.66129983119378
C        -3.93180749863264   -4.97693065804695    2.50466628003535
O        -3.23002372444458   -5.95436935588729    2.34711260537426
O        -4.81527419583239   -4.88706815306488    3.48577836275190
C         1.30773779554915   -0.25309301959393   -0.59578869719661
C         1.70482164624997    0.52016079632079   -1.59478220848447
C         1.25347840861395    1.92843499691692   -1.85344033135130
C         2.42280505925176    2.86429894850703   -1.75864547680825
C         2.87895488218787    3.69287596638285   -2.68530861691190
C         2.30992187377587    3.94304174297415   -4.05221746537061
C         1.87373882995525    5.37790022592659   -4.15102414326789
C         0.63346768603561    5.83850317743099   -4.09546224203708
C        -0.62755892501385    5.04244688509619   -3.95964943664637
C        -1.41853425480036    5.04578029173202   -5.26934857855407
H        -0.65713943994417    0.30340749581595   -0.00480734875761
H         0.62180259917137    1.05502334214483    0.94711137794833
H         1.16445827559057   -1.17984152556732    1.93951188735432
H        -0.18544917450328   -1.88421274225030    1.05845797746232
H        -0.33887197134966    0.31841099181170    3.16538998408449
H        -0.73714838622150   -1.37446954997978    3.42114751069280
H        -2.21494132954414    0.61809437621273    1.65048488000643
H        -2.75220955096617   -0.03618410296240    3.19118976486633
H        -2.39742899453246   -1.62493645694754    0.60950485094976
H        -3.91776257835436   -1.06157673749489    1.29324183241099
H        -3.47541824227772   -2.44887299277933    3.34342552336797
H        -2.03025436517428   -3.09758362324348    2.55675866056721
H        -4.89055409633867   -3.35413127228939    1.52642504875395
H        -3.43703836488151   -3.98134540762188    0.69634211022766
H        -4.82582109478545   -5.67637246258468    4.06119576088667
H         1.71069214888921   -1.25463409211304   -0.51926148833756
H         2.43231046834510    0.14599724361694   -2.30371879822532
H         0.79993888921017    1.97577193017272   -2.84452819156146
H         0.50309299437866    2.22357829167773   -1.11804224438080
H         2.94282509128200    2.81199524581537   -0.80955746127138
H         3.74342968538185    4.30318043479685   -2.45293881749533
H         3.09624130603639    3.76898089227324   -4.79280282788311
H         1.48511215094566    3.26878448391510   -4.26826261076033
H         2.68810273610935    6.08594292872203   -4.24318166598488
H         0.47534994317858    6.90666095660339   -4.18442716052573
H        -0.41057182407636    4.01689911787451   -3.66466700645871
H        -1.23997290653165    5.49231096487131   -3.17414100923530
H        -0.83430595315378    4.58660671183531   -6.06366407245794
H        -1.65800931798713    6.06433432820466   -5.56631510653888
H        -2.34642230766910    4.49097948046674   -5.15430530817151

**Comment by jouteurestaque** [comment]
but if I add 3 more so a total of 6 doubles bond compared to the 2 from the failing one
I get 5206 conformers

56
 energy: -71.437156524748 gnorm: 0.000551576388 xtb: 6.4.1 (afa7bdf)
C         1.59008703040016   -1.16360898994732    0.40191370726537
C         1.99351884898124   -2.05635522785042   -0.48913032540192
C         2.30537865516419   -1.80179325567461   -1.93764984077622
C         1.08175181912029   -2.08357345666749   -2.76519251472222
C         0.80172568318169   -3.21765962226259   -3.38872440787507
C         1.66737259328823   -4.44675559402789   -3.42963728666667
C         2.47482800734144   -4.44924995376852   -4.69640579917892
C         3.79370253370741   -4.40672741856302   -4.80941502369999
C         4.80615077442151   -4.37034118163921   -3.70721753699531
C         5.92084651896434   -5.35171133844415   -3.93672336212892
C         7.07910532186555   -5.33004965895733   -3.29472467563591
C         7.45140916243740   -4.29849253754861   -2.26484468154802
C         7.86502080800739   -3.02202190448258   -2.94037481898189
C         7.43916522221973   -1.79497784381079   -2.67907634283448
C         6.48100928104523   -1.37263336256193   -1.60093909344339
C         7.27543265444558   -0.79139747627855   -0.46556052584208
C         7.40278982690120    0.50861806988920   -0.23324028617096
C         8.23620646748802    1.10629992436418    0.85615122722866
C         7.41876161786450    2.04422628947352    1.74503342081777
C         1.39338882025947    0.30421888165617    0.17579376162768
C         2.48205738951083    1.11671884881294    0.90108866854494
C         3.82045150893803    0.79916769834310    0.28863374815371
O         4.14734252031907    1.10126706938107   -0.83981396639236
O         4.61059068840500    0.12750466611662    1.10768104025223
H         1.40098118261620   -1.48813308047596    1.41720582651321
H         2.07564944382355   -3.09219350728635   -0.18639471528156
H         3.12721395047533   -2.44413255418504   -2.25121245148783
H         2.61330107961074   -0.76619538239329   -2.08874434372061
H         0.36451292953062   -1.27383651600114   -2.80083270523974
H        -0.11400693801614   -3.28625227868482   -3.96176119721495
H         1.01987037731797   -5.32807993027858   -3.42737765450671
H         2.30877132801198   -4.49330863203641   -2.55279970847149
H         1.87544114509404   -4.46196122537244   -5.59871045927148
H         4.22710417732443   -4.39258763032444   -5.80247166628130
H         5.22926537847035   -3.36124689917485   -3.65220527493448
H         4.33970024279952   -4.58576651164686   -2.74223548790605
H         5.72652561314742   -6.12375729390598   -4.66893048294705
H         7.83215298935825   -6.07029334351710   -3.52677107455651
H         8.29342501791738   -4.66749452736152   -1.67404539729488
H         6.61419450304052   -4.12365502169384   -1.58912256937566
H         8.58366365318126   -3.16240688248805   -3.73849663142144
H         7.84435352286073   -0.97017129613718   -3.25162657573724
H         5.79909254317989   -0.61646780426051   -1.99788869840610
H         5.89605069618161   -2.22190854160231   -1.24524324790597
H         7.81452043865140   -1.50938541534878    0.13934606886916
H         6.87612753858836    1.22035460118216   -0.85865445617246
H         8.68247597747697    0.31477607744552    1.46067667053781
H         9.04773063021230    1.67773336003842    0.39617577318863
H         6.64014060882367    1.49577434118908    2.27046109079915
H         6.94691153644396    2.81973256510844    1.14479397155002
H         8.06041936764820    2.52162487762391    2.48115334582401
H         0.42092043751321    0.59977797867731    0.57287288696600
H         1.42065015257786    0.54692308750030   -0.88594056259969
H         2.50945836060203    0.86330074201498    1.95968088062159
H         2.28424348107376    2.18096900100412    0.77304769200568
H         5.48095488019523   -0.08912498317959    0.69643606824297

**Comment by pprcht** [comment]
This could happen if the PES becomes more flat and more minima end up in the 6 kcal energy window. With such flexible molecules it is sometimes hard to say. But the amounts of conformers certainly sound plausible.

**Comment by jouteurestaque** [comment]
thank you.

**Comment by moabe84** [comment]
Hi Philipp,
I'm also facing this issue. Have you been able to fix it? Thanks.

Mostafa

**Comment by pprcht** [comment]
If it is also in the GC part for you, you may try the 3.0dev version, as I suggested above.
The GC routines were revised from scratch in there, which hopefully avoids this error entirely.

**Comment by moabe84** [comment]
Yes, it happens in the GC part. 
Is this the 3.0dev version:
https://github.com/crest-lab/crest/releases/download/latest/crest-latest.tar.xz

**Comment by pprcht** [comment]
Hm no, there the continuous release is build from the main branch. You can either build it yourself from the respective branch, or use this: [crest.zip](https://github.com/crest-lab/crest/files/12313498/crest.zip)
Please keep in mind this is a preliminary version while using it.

**Comment by moabe84** [comment]
Great. I'll try it and let you know about the results. Many thanks.

**Comment by moabe84** [comment]
Hi Philipp,
I'd like to update you that the problem has been resolved using the 3.0dev version. Thank you very much.

**Comment by pprcht** [comment]
Thanks for letting me know!
