### ISSUE TITLE
Selective Bias Potentials?

### ISSUE THREAD

**Issue by ConstantinJa** [crest-lab/crest#199]
Good afternoon.

Im attempting to identify the most favorable binding sites for the adsorption of water into a metal organic framework. To this end, I performed metadynamics in the nci mode for one or multiple water molecules located at the centre of a tetrahedral binding site of the solid.  Unfortunately, the bias potential quickly drives the adsorbate out of the cavity and proceeds to sample its (uninteresting) exterior. Is it possible to implement additional bias potentials which act only on a certain set of atoms, thus allowing me to softly constrain the water inside the binding pocket without affecting the rest of my model? Im sure such a functionality would be of great use for a variety of projects. For now, Im blocking the open faces of the tetrahedron with argon atoms which I remove afterwards for refined analysis but theres certainly a better way to accomplish this.

Thank you in advance.

Regards, Constantin

**Comment by pprcht** [comment]
Hi,
It is possible to specify on which atoms the metadynamics potential should act (and on which not).
This is used for example in the [constrained sampling](https://crest-lab.github.io/crest-docs/page/examples/example_4.html#fixing-of-entire-substructure-parts) and can be included via the `$metadyn` block of a constraints file. I believe this is what you might want to do

**Comment by pprcht** [comment]
I'm not talking about additional constraints, only the `$metadyn` block. If you exclude the atoms corresponding to the water molecules there, the metadynamics shouldn't push them out.
Defining multiple force constants sadly isn't possible in the xtb constraints, as far as I am aware.

**Comment by ConstantinJa** [comment]
Ah I tried that but sadly it gets pushed out anyway

**Comment by pprcht** [comment]
Another thing you could try is to specify a wall potential that is _only_ acting upon the water molecules, e.g. of similar size as the cavity. That is the same trick the QCG procedure uses to keep the solute in the middle of a solvent cluster

**Comment by ConstantinJa** [comment]
Alright I misunderstood 'This could be used to confine different fragments in different sized spheres. The only restriction is that the potential shape is global.' as 'the potential acts on all atoms as a linear combination of the individual potentials' now it works as desired thank you
