### ISSUE TITLE
chemical bonds changes during TS search of CREST

### ISSUE THREAD

**Issue by gantang126** [crest-lab/crest#200]
Hello,

I have a problem of changed chemical bonds during the constrained conformer searching via CREST.

I want to study the TSs of addition of cyanide towards the ketones, thus I fixed the distance of C1-C(CN) (ca. 2.4 Å). but the resulted conformers have the new bond between C2 and Cα, still the distance between C1 and C2 remain nearly 2.4 Å.

I notice the CREST program would automatically set shake =2. Therefore, I am wondering why the chemical bond still changed?
I also tried to set shake, but still the same result occurred.

Could you give me some suggestion?

My .xcontrol file is shown as below.
```
$constrain
  atoms: 44,212-214,226
  force constant=2.0
  reference=coord.ref
$metadyn
  atoms: 1-43,45-211,215-225,227-250
$md
  shake=2
$end
```

**Comment by pprcht** [comment]
Hello,
The shake setting only affects the MD/metadynamics, it doesn't do anything for the subsequent geometry optimization.
You will need to define additional constraints to the control file for that. The list of available things you can constrain can be found here: https://xtb-docs.readthedocs.io/en/latest/xcontrol.html?highlight=constraints

**Comment by gantang126** [comment]
Thanks you so much.
I will read the link carefully.

Thanks pprcht again for the prompt reply.
