### ISSUE TITLE
QCG is having issue with adding a large number of solvent molecules 

### ISSUE THREAD

**Issue by iconrun** [crest-lab/crest#202]
Hello, 

I'm using the QCQ extension of CREST to create a water cluster (200 water molecules) around frozen stacked chromophores. The problem appears during the addition of the 93rd water molecule to the system. Below, I've attached the last lines of the output file. I was trying to change various parameters such as --wscal, -mdtime, --mddump, but the problems occurred exactly at the same step. I would like kindly ask to any help, suggestion or advice. 

` 92  -615.535733  -16.42   -1229.06       1.362    -32.902     14.2  21.3   19243.3   normal
 Cluster energy not found 
Total Energy of cluster not found.
93     0.000000 *******   ********       1.357      0.000     14.3  20.2   19459.7   normal`

**Comment by cplett** [comment]
Hi,
This might be indeed a problem of the wall potential that becomes too small.
If you can send me your input coordinates, please, then I can check on this.

**Comment by iconrun** [comment]
Hi,

Thank you very much for your help. I've attached the input coordinates.


czw., 1 cze 2023 o 13:06 Christoph Plett ***@***.***>
napisał(a):

**Comment by cplett** [comment]
Hi,
I tested the system with 200 water molecules and it seemed to work for me:
![200_water](https://github.com/crest-lab/crest/assets/82893466/6e13e329-7782-47bd-8ab9-481176bcdd87)
I guess that this might be an issue of an older version. Can you, please, tell me if you use a `crest` version you compiled from the source code or a release and if you use the old `xtbiff` or the new aISS algorithm of `xtb` to grow the cluster?
Then, I can check on the specific version.

**Comment by iconrun** [comment]
Hi, 

Thank you for sending the results. 

According to the visualisation of the system, I guess that the NADH molecule was not constrained during the adding water molecules. The final NADH structure surrounded by 200 water molecules is quite far from the starting structure, which I must maintain during the cluster growth. To constrain the NADH molecule, I added '--cinp constrain' to the command line. Could it be a problem for growing the cluster? 

The contents of the constrain file:
$constrain
  atoms: 1-71
$end

I use the release versions of a crest (2.12), xtb (6.6.0), and xtbiff (1.1) downloaded from the github. According to my understanding, I've been using only the crest with the xtbiff algorithm. Is there a way to force using the new aISS algorithm of xtb to grow the cluster?  

Thank you in advance for your help.

**Comment by cplett** [comment]
Hi,
Currently, only a crest version build with the source code is able to use the aISS. This will be the default then.
Regarding the fixed solute, you can use the `--fixsolute` and `--nopreopt` flags to keep the solute fixed during the growth.
For the ensemble you will indeed require the xcontrol. 
I will check this and also the version with the xtbiff.

**Comment by pprcht** [comment]
@cplett actually the [continous release](https://github.com/crest-lab/crest/releases/tag/latest) should include the aISS usage capability, shouldn't it?

**Comment by cplett** [comment]
Somehow, the [continuous release](https://github.com/crest-lab/crest/releases/tag/latest) didn't update after the last commits.

**Comment by pprcht** [comment]
According to the description the release has the status of commit #189 of April 3rd, so it should be up to date. You can clearly see the binaries were uploaded on that date. The release tag never changes from Dec 23, 2022.

**Comment by iconrun** [comment]
Thank you for all your suggestions. 

I tested the aISS algorithm for the cluster growth from the [continuous release](https://github.com/crest-lab/crest/releases/tag/latest), and it has the same problem as the xtbiff. When I freeze the solute (using the .xcontrol file and adding the --fixsolute and --nopreopt flags), I cannot add more than 94 water molecules to the system. Formally, the NADH molecule has a charge of -2. Manipulating the charge, I wanted to check whether the negatively charged system could affect the cluster growth, but it's not. 

Any advice would be appreciated.

**Comment by cplett** [comment]
Hi,
I tested a little bit more (also with fixed solute and `xcontrol` file), but I didn't observe a crash of the program.
For further evaluation, it would be great if you could provide me the whole output of crest, please.

**Comment by iconrun** [comment]
Hi, 

I've attached the whole printout of crest. Thank you.
[nadh-crest-qcg.zip](https://github.com/crest-lab/crest/files/11743133/nadh-crest-qcg.zip

**Comment by cplett** [comment]
Hi,
It seems that a xtb optimization somehow crashed. Did you give the program enough stack size by configuring the `.bashrc` (if you are working on a Linux computer?
Helpful settings are:
ulimit -s unlimited
export OMP_STACKSIZE=4G
export OMP_NUM_THREADS=<ncores you want to use>,1
Further instructions can be found [here](https://xtb-docs.readthedocs.io/en/latest/setup.html#id5).

**Comment by iconrun** [comment]
Hi, 

Thank you for the suggestions. Increasing the value of the OMP_STACKSIZE variable helped. I tested both the aISS and xtbiff approaches, and everything works.
