### ISSUE TITLE
Error when running crest for pyrene dimer molecules

### ISSUE THREAD

**Issue by haobamkisan** [crest-lab/crest#206]
Dear All, 
I ran pyrene dimer molecules by implementing the spherical log fermi constraining potential and the command line I used is  "crest struc.xyz -nocross -cinp constrain.inp". However, I have encountered the following error, and also I  have attached the details of struc.xyz and constrain.inp file 

 Command line input:
 > crest struc.xyz -nocross -cinp constrain.inp

  -nocross  : skipping GC part.
  -cinp : constrain.inp

 <constrain.inp> file present.
 content of the constraining file (sorted):
> $wall
>   potential=logfermi
>   sphere: 17, all

 -------------------------
 xTB Geometry Optimization
 -------------------------

  Initial geometry optimization failed!
  Please check your input.

###########
constrain.inp
$wall
   potential=logfermi
   sphere: 17, all
$end

#########
struc.xyz
   58
 
 C          3.5632730000       -0.8309560000       -1.6793250000
 C          4.3718880000       -0.6616260000       -0.5647920000
 C          3.8358940000       -0.7478500000        0.7117640000
 C          2.4768240000       -0.9998000000        0.8954720000
 C          1.6469550000       -1.1644390000       -0.2365180000
 C          2.1997740000       -1.0832760000       -1.5346510000
 C          0.2503610000       -1.4054910000       -0.0689760000
 C         -0.3047270000       -1.4777410000        1.2284590000
 C          0.5665920000       -1.3122950000        2.3640070000
 C          1.8852820000       -1.0882170000        2.2069730000
 C         -0.5803540000       -1.5691600000       -1.2003630000
 C         -1.9430890000       -1.7964870000       -1.0158670000
 C         -2.4839740000       -1.8626370000        0.2587840000
 C         -1.6727530000       -1.7031490000        1.3715120000
 C          0.0121000000       -1.4871940000       -2.5113250000
 C          1.3293430000       -1.2559780000       -2.6705780000
 H          3.9876670000       -0.7657730000       -2.6764310000
 H          5.4310930000       -0.4644310000       -0.6922620000
 H          4.4736420000       -0.6176270000        1.5805600000
 H          0.1303840000       -1.3682990000        3.3561430000
 H          2.5310180000       -0.9651370000        3.0709680000
 H         -2.5833820000       -1.9109450000       -1.8846490000
 H         -3.5485800000       -2.0228200000        0.3850640000
 H         -2.1008790000       -1.7429550000        2.3680010000
 H         -0.6347460000       -1.6102360000       -3.3740430000
 H          1.7622460000       -1.1904830000       -3.6641020000
 H         -6.5295752900        4.4949024900        2.3962382100
 C         -6.1051712900        4.5600534900        1.3991352100
 C         -6.9137382900        4.3906104900        0.2845842100
 C         -6.3777062900        4.4767584900       -0.9919597900
 H         -7.0154532900        4.3465674900       -1.8607627900
 C         -5.0186702900        4.7289284900       -1.1756667900
 C         -4.4271422900        4.8174094900       -2.4871657900
 H         -5.0728482900        4.6941324900       -3.3511547900
 C         -3.1084592900        5.0415234900       -2.6441877900
 H         -2.6721572900        5.0974884900       -3.6362837900
 C         -2.2371372900        5.2068044900       -1.5086117900
 C         -0.8691392900        5.4323824900       -1.6516667900
 H         -0.4409992900        5.4721704900       -2.6481507900
 C         -0.0579402900        5.5919484900       -0.5389367900
 H          1.0066827100        5.7520294900       -0.6651997900
 C         -0.5988182900        5.5257134900        0.7357122100
 C         -1.9615352900        5.2982894900        0.9202092100
 C         -2.5540012900        5.2162604900        2.2311632100
 C         -3.8712592900        4.9851324900        2.3904022100
 H         -4.3041502900        4.9195464900        3.3839252100
 H         -1.9071512900        5.3392434900        3.0938862100
 H          0.0415237100        5.6398264900        1.6045032100
 C         -2.7922222900        5.1345074900       -0.2111767900
 C         -4.1888372900        4.8935744900       -0.0436577900
 H         -7.9729692900        4.1935354900        0.4120182100
 C         -4.7416752900        4.8124034900        1.2544662100
 C          0.8098070000       -1.2328790000        0.3217870000
 C          0.8098070000       -1.2328790000        0.3217870000
 C          0.8098070000       -1.2328790000        0.3217870000
 C          0.8098070000       -1.2328790000        0.3217870000
 C          0.8098070000       -1.2328790000        0.3217870000
 C          0.8098070000       -1.2328790000        0.3217870000

Thanks
Kisan

**Comment by pprcht** [comment]
Hi,
since the calculation fails in the initial xtb optimization there should be a file `xtb.out` that might give you some indication on what went wrong. Have a look in there and maybe try testing with xtb first before attempting to run the calculation with CREST.

A thing that occasionally happens with the wall potentials is that the sphere is too small, that could be a cause here. In the [continuous release](https://github.com/crest-lab/crest/releases/tag/latest) there is also a command line argument `--wall`/`--wallxl`/`-wallxxl` that automatically creates such a potential, maybe that's of interest for you.

**Comment by haobamkisan** [comment]
In the xtb.out the following lines are written


           -------------------------------------------------
          |                Calculation Setup                |
           -------------------------------------------------

          program call               : xtb tmpcoord --gfn2 --opt
          coordinate file            : tmpcoord
          omp threads                :                     1

   ID    Z sym.   atoms
    1    6 c      1-16, 28-30, 32, 33, 35, 37, 38, 40, 42-45, 49, 50, 52-58
    2    1 h      17-27, 31, 34, 36, 39, 41, 46-48, 51
spherical wallpotenial with radius    8.9960134 Å

molecular fragmentation (1/2 indicates fragments):
1111111111111111111111111122222222222222222222222222111111
# atoms in fragment 1/2:    32    26
 fragment masses (1/2) :      274.32      202.25
CMA distance (Bohr)    :  14.479
constraining FC (au)   :  0.0500
########################################################################
[ERROR] Program stopped due to fatal error
-17- Some atoms in the start geometry are *very* close
-16- XTB REFUSES TO CONTINUE WITH THIS CALCULATION!
-15- Found *very* short distance of  0.000E+00 for c57-c58
-14- Found *very* short distance of  0.000E+00 for c56-c58
-13- Found *very* short distance of  0.000E+00 for c55-c58
-12- Found *very* short distance of  0.000E+00 for c54-c58
-11- Found *very* short distance of  0.000E+00 for c53-c58
-10- Found *very* short distance of  0.000E+00 for c56-c57
-9- Found *very* short distance of  0.000E+00 for c55-c57
-8- Found *very* short distance of  0.000E+00 for c54-c57
-7- Found *very* short distance of  0.000E+00 for c53-c57
-6- Found *very* short distance of  0.000E+00 for c55-c56
-5- Found *very* short distance of  0.000E+00 for c54-c56
-4- Found *very* short distance of  0.000E+00 for c53-c56
-3- Found *very* short distance of  0.000E+00 for c54-c55
-2- Found *very* short distance of  0.000E+00 for c53-c55
-1- Found *very* short distance of  0.000E+00 for c53-c54
########################################################################
"xtb.out" 119L, 5657C

**Comment by pprcht** [comment]
Well, your input geometry is broken. You have specified the same Cartesian position for multiple atoms (the last six in your input file, it seems). No calculation will work with this, you need to repair it first.

**Comment by haobamkisan** [comment]
Thank You !
The error is there in the coordinates.

**Comment by haobamkisan** [comment]
Hi,

I used sphere logfermi potential with radius of 20 Bohr for dimer molecules, and the calculation is terminated normally and generates the conformers. How can I visualize the origin of the sphere potential and the molecule's center of mass coincide?

**Comment by pprcht** [comment]
Hi,
Both the center of mass and the wall potential's center are automatically shifted to the origin on multiple occasions between calculations. 
You could (only for visualization!) add another atom (e.g. Xe) at the origin and then use your favorite molecule viewer.

**Comment by haobamkisan** [comment]
Thank You !
