### ISSUE TITLE
Rotamer file blows up in conformational search

### ISSUE THREAD

**Issue by kashout** [crest-lab/crest#207]
Hi,

I'm running a conformational search in crest (v 2.12) with the following command line input:

> crest CREST_test_stereo1_1.txt --gfn2 --noreftopo --notopo h,li,na,k,cs --chrg -1 --uhf 0 -T 16 > CREST_test_stereo1_1.log

but have to cancel the job after about an hour because the crest_rotamers_2.xyz file reaches a size of 1.4 TB! This has happened on multiple attempts using the same input geometry, although all my other runs work great.

Most importantly, I'm assuming this is not the expected behavior, and it should throw some error before reaching this point. Is there a fix that would terminate the run early if this occurs?

And secondly, can this be prevented in a way other than changing the input structure?

Thanks a lot for any help!

(file extensions below have been changed to be compatible with GitHub)
[CREST_test_stereo1_1.log](https://github.com/crest-lab/crest/files/12001808/CREST_test_stereo1_1.log)
[CREST_test_stereo1_1.txt](https://github.com/crest-lab/crest/files/12001809/CREST_test_stereo1_1.txt)

**Comment by kashout** [comment]
Thanks for the quick reply!
About the file contents, I've attached the first and last 5000 lines of the rotamer output, which paints a clear picture of the total file I think. Somehow all coordinates of the final few structures are all NaN, where the final structure is about 300.000 lines, with some additional gibberish.

For this run I used the conda-forge binaries. I'll check if I can install the continuous release and rerun the geometry.

Computations are run on a large cluster using slurm, and get assigned to random nodes each time. I don't have access to another linux machine at the moment, so will this will take some time to check.

[head.txt](https://github.com/crest-lab/crest/files/12002080/head.txt)
[tail.txt](https://github.com/crest-lab/crest/files/12002081/tail.txt)

**Comment by pprcht** [comment]
Yep, that is just nonsense in there. I don't know where it comes from, but my suspicion is that it is something with the binary/machine, rather than the code itself.

**Comment by kashout** [comment]
Weirdly enough, I'm not able to reproduce the error from the exact same input after a reinstall from the conda-forge binaries, although the xtb and crest versions are the same...
The first trial MTD run now directly converges, and everything runs smoothly after (see output below).
Not a very satisfactory solution, but thank you for helping out!

[CREST_test_stereo1_1.log](https://github.com/crest-lab/crest/files/12163186/CREST_test_stereo1_1.log)

**Comment by pprcht** [comment]
Sure. Feel free to contact if other help is required.

As a side note, it might be worth trying other binaries than the conda version since it is a bit old. There is a continuous release version with prebuild binary from the latest main branch commit [here on GitHub](https://github.com/crest-lab/crest/releases).
