### ISSUE TITLE
Error in  conformational search

### ISSUE THREAD

**Issue by haobamkisan** [crest-lab/crest#208]
Hi 
I am running a conformational search with the following command line:

> crest bb_ethylcatehol.xyz --chrg 4 --gfn2 --gbsa h2o -T 2

However, the code suddenly stop after writing few line

 ========================================
            MTD Iteration  1
========================================

     ========================================
     |         Meta-MD (MTD) Sampling       |
     ========================================

Starting Meta-MD   1 with the settings:
     MD time /ps        :     7.0
     dt /fs             :     5.0
     dumpstep(trj) /fs  :     100
     dumpstep(Vbias)/ps :     1.0
     Vbias factor k /Eh :  0.2760
     Vbias exp α /bohr⁻²:    1.30
Starting Meta-MD  14 with the settings:
     MD time /ps        :     7.0
     dt /fs             :     5.0
     dumpstep(trj) /fs  :     100
     dumpstep(Vbias)/ps :     1.0
     Vbias factor k /Eh :  0.4600
     Vbias exp α /bohr⁻²:    0.80

Please give me some suggestions.

**Comment by pprcht** [comment]
What do you mean with suddenly stop? Is there an error message? Does the program terminate or is crest or xtb still running in the background (have you checked in `htop`)?

**Comment by haobamkisan** [comment]
When I change T 2 to T 3 it is running fine.
