### ISSUE TITLE
Crest is terminated without giving error msg

### ISSUE THREAD

**Issue by chem-ys** [crest-lab/crest#209]
It works with the small monomer system, but when I do the same calculation with the large two molecule (~150atoms) It does not give me the results(crest_conformers.xyz) only giving the crest.out without error msg. I attached the run.sh and job script files. and with the working_well.xyz it works fine but with the trouble_one.xyz, calcualtion dies..

[run.sh.txt](https://github.com/crest-lab/crest/files/12104547/run.sh.txt)
[YS_YSP3_Sx4_MCNC4.job.txt](https://github.com/crest-lab/crest/files/12104548/YS_YSP3_Sx4_MCNC4.job.txt)
[working well.xyz.txt](https://github.com/crest-lab/crest/files/12104549/working.well.xyz.txt)
[trouble_one.xyz.txt](https://github.com/crest-lab/crest/files/12104550/trouble_one.xyz.txt)
[trouble_one_crest.out.txt](https://github.com/crest-lab/crest/files/12104551/trouble_one_crest.out.txt)
[working_well_crest.out.txt](https://github.com/crest-lab/crest/files/12104656/working_well_crest.out.txt)

**Comment by pprcht** [comment]
Hi,
Something about the initial xtb calculations seems off in your printout. First of all, the xtb printout shouldn't be there, but second it fails to perform the calculations for some reason. If the latter is true for all subsequent xtb calculations there won't be any output processable by crest. 
That said, I get both of your systems to run and can't reproduce this error. Have you tried using newer versions of the programs? Newer versions of both crest and xtb are available.
