### ISSUE TITLE
Implementation of the "restart" option

### ISSUE THREAD

**Issue by moabe84** [crest-lab/crest#212]
Dear Crest team,
I'm wondering if the restart option has already implemented. I noticed from [this post](https://github.com/crest-lab/crest/issues/14) that it's been asked multiple time. I think it's going to be very useful feature particularly for large molecular systems. Thanks.

Mostafa

**Comment by pprcht** [comment]
I will try to include it in the upcomming version

**Comment by moabe84** [comment]
That's great. Thank you. When will the new version be released?

**Comment by moabe84** [comment]
Thanks for the info. I look forward to it.

**Comment by kainszs** [comment]
Hi, 
are there any updates on this?
Best regards, Kai

**Comment by pprcht** [comment]
Hi,
I've implemented a framework for this with 3.0, but it needs some cross-checking. I'll get back to you about it.

**Comment by sandipgiri576** [comment]
is it available now?
