### ISSUE TITLE
How can I set FOD in CREST?

### ISSUE THREAD

**Issue by FreemanTheMaverick** [crest-lab/crest#215]
Dear developers,

The system I am working on has strong static correlation. In xTB, I can use the keyword `--fod' to set FOD, but what about in CREST2? I don't find any similar keywords in CREST doc. Would you please tell me how to set FOD in CREST? Thank you!

**Comment by pprcht** [comment]
Technically you could set `fod='true'` in a separate input file and let CREST pass it to the xtb calculations with `--cinp <inputfilename>`.
However, there is no printout about the FOD from the side of CREST and the cub files will get deleted together with the rest of xtb output. I don't think you want the overhead for something you won't even see in the end.
The easiest thing would probably be to run singlpoints to get FODs *separately* with xtb on the final ensemble.

**Comment by FreemanTheMaverick** [comment]
> Technically you could set `fod='true'` in a separate input file and let CREST pass it to the xtb calculations with `--cinp <inputfilename>`. However, there is no printout about the FOD from the side of CREST and the cub files will get deleted together with the rest of xtb output. I don't think you want the overhead for something you won't even see in the end. The easiest thing would probably be to run singlpoints to get FODs _separately_ with xtb on the final ensemble.

Thank you for answering! As far as I know, `--cinp` is meant for constraints only, since this keyword appears in the "Constraining Options" section. Can I put `fod='true'` in that file?

**Comment by pprcht** [comment]
Yes, you can put anything in there that shall be passed to xtb.
But again, be aware that you won't see any FOD output by CREST and the files might be deleted in the cleanup.

**Comment by FreemanTheMaverick** [comment]
> Yes, you can put anything in there that shall be passed to xtb. But again, be aware that you won't see any FOD output by CREST and the files might be deleted in the cleanup.

Do you mean that even if FOD is set, single point energy and/or gradient computation will still be done as simple Restricted HF/KS? Well actually I am working on the coupling of two radicals and the TS should be an open shell singlet. Theoretically, can xTB find this TS with keyword 'FOD'?

**Comment by pprcht** [comment]
What I meant is that there will be no printout indicating that there was anything different about the calculations. But the calculations *will* be done as you specify with `--cinp`

From the open-shell aspect I would have assumed you might need to set xtb's UHF parameter to 2 (=n<sub>alpha</sub>-n<sub>beta</sub>) to enforce such a solution. Keep in mind that the xtb variants are by design spin-restricted treatments and  have no spin-discriminating terms. It might be that the FOD or UHF gets you somewhere, but I really can't tell.

**Comment by FreemanTheMaverick** [comment]
> What I meant is that there will be no printout indicating that there was anything different about the calculations. But the calculations _will_ be done as you specify with `--cinp`
> 
> From the open-shell aspect I would have assumed you might need to set xtb's UHF parameter to 2 (=nalpha-nbeta) to enforce such a solution. Keep in mind that the xtb variants are by design spin-restricted treatments and have no spin-discriminating terms. It might be that the FOD or UHF gets you somewhere, but I really can't tell.

I see. It is very kind of you to have explained this to me. One last question: how can I set '--etemp=5000' in the input file?

**Comment by pprcht** [comment]
You can add it in a `$scc` section like
```
$scc
temp=5000
```

**Comment by FreemanTheMaverick** [comment]
> You can add it in a `$scc` section like
> 
> ```
> $scc
> temp=5000
> ```

This section does not seem to be in the doc, but it worked. Thank you! I would not be able to proceed with my project without your help!
