### ISSUE TITLE
Error in --entropy mode

### ISSUE THREAD

**Issue by cassguff** [crest-lab/crest#220]
Perhaps I am not fully understanding the process for calculating entropy as explained in the documentation (https://crest-lab.github.io/crest-docs/page/examples/entropy.html) and the paper (https://pubs.rsc.org/en/content/articlelanding/2021/SC/D1SC00621E). Based on my understanding of the process, I am doing the following:

1. Running CREST with defaults to get the lowest energy structure
2. Taking that crest_best structure and further optimizing (I am doing DFT opt-freq calculations in Gaussian).
3. Using the coordinates from that further optimized result as the input for CREST using --entropy.

It gets mostly through the workflow, then in the frequency calculations it gets stuck and terminates. This is what I see (it's a small molecule I'm testing it with):

##
 --------------------------------------
 FINAL CALCULATION OF MOLECULAR ENTROPY
 --------------------------------------

WARNING: not enough blocks

FINAL ENTROPY (max conf.)  :      0.65254

 ----------------------------------
 Frequency Calculation and Averages
 ----------------------------------
 Nconf on file      : 5
 Taken for Hessians : 2 (= 98.63% total population)
 T range  /K    :   278.15   378.15
 scaling factor :          1.000000
 rotor cutoff   :         25.000000 cm⁻¹
 imag. cutoff   :        -50.000000 cm⁻¹

 Running 2 calculations ...
 1 2 done.

 calculating averages for G and S ...    done.
 calculating Boltzmann weights ...       done.
 calculating reference S (bhess) ... error while reading input coordinates
##

Are we supposed to provide CREST with the frequencies from the DFT calculation? If so can you point me in the direction of where in the documentation it outlines how to do this?

Thank you.

**Comment by pprcht** [comment]
Hm from what you describe you should be fine. 
CREST doesn't need to know about the actual DFT frequencies, it should provide you with a *S*<sub>conf</sub> that can be added to your DFT *S*<sub>vib</sub>.  To provide a purely additive *S*<sub>conf</sub> term, CREST calculates a reference *S*<sub>vib</sub> for your DFT input structure at the GFN level and substracts it from the ensemble average. That's the step where it seemingly failed.

As for *why* it fails, apparently it didn't like some structure attempted to read there. Could be that the xtb IO was changed, but I need to check. What versions xtb and CREST are you using?
For now you could try using the `--noref` flag to turn this bhess calculation off.

**Comment by cassguff** [comment]
I am using CREST version 2.10.2 and xtb 6.3.2. I can try installing newer versions and see if that fixes it.

**Comment by pprcht** [comment]
The *Chem. Sci.* paper you mentioned above was done with 2.11, all implementations regarding the conformational entropy preceding this version must be considered not fully functional for the runtype.

Maybe try the 3.0dev version, I recently cross-checked the entropy runtype there and know it works.

**Comment by cassguff** [comment]
Using a newer version of xtb seems to solve the problem. Thank you.

Is is possible to get results for a custom temperature range? (larger range than 278.15-378.15K that is default)?

**Comment by pprcht** [comment]
That's good.

Adjusting the temperature range is possible. [Look here](https://crest-lab.github.io/crest-docs/page/documentation/keywords.html#entropy-mode-settings). You want the the `-trange` option

**Comment by cassguff** [comment]
I am trying to replicate the Cp results for n-octane from Figure 7 in that
paper to make sure I have the program working correctly, but I cannot seem
to get the same results. The Cp,Conf(T) I got has 2 maxima and has lower
values than are shown in Figure 7. What might I be doing differently?

**Comment by cassguff** [comment]
My research is in heat capacity, so I am very interested in using this tool
if I can. I am trying to replicate the examples in the paper for tamiflu to
make sure I am doing it correctly to compare both S_conf and Cp_conf. I am
using the input files that were provided online (
https://github.com/grimme-lab/mol-entropy) and I've tried
*crest gfnff.xyz <http://gfnff.xyz> --entropy --gfnff --trange 20 1500 20*
and
*crest gfn2.xyz <http://gfn2.xyz> --entropy --gfn2 --trange 20 1500 20*

From Figure 8 it looks like Sconf should be around 15-16cal/mol/K and I got
13.59059 cal/mol/K and 12.951106 cal/mol/K for GFN-FF and GFN2,
respectively. I attached the Cp_conf graphs to compare to Figure 7 and I
noticed the curves do not go up as high as shown in Figure 7 for tamiflu.
[image: image.png]

I am using version 2.12 of CREST and version 6.6.1 of xtb. I tried using
CREST version 2.11 too because that's what was used for the publication and
that didn't change it. Do you have any ideas of what I may be doing
incorrectly?

**Comment by pprcht** [comment]
Ah, I think I have an idea whats happening, although I would need to see the printout to confirm.
I think you are not doing anything wrong, but our naming conventions are a bit confusing.

If you look at tamiflu in Fig.3, you can see that the conformational (or, more correctly, the *configurational*) entropy gets extrapolated to a value around 14 cal/molK. This is the value corresponding to the Gibbs-Shannon entropy in Eq.8. In the final program printout we are calling this `Sconf`

To get to the value around 16 cal/molK you need to add the ensemble average from Eq.11, which in the program printout should be called `δSrrho`.

And the entire *conformational* term, which is somewhat misleadingly called `S(total)` (=`Sconf` + ` δSrrho`) the program printout, is what is plotted in Fig.8. According to my backup data this accounts to ~16.04 cal/molK for tamiflu at GFN2-xTB level.

To get the *absolute* entropy of your molecule this `S(total)` needs to be added to your DFT *S*<sub>vib</sub>+*S*<sub>rot</sub>+*S*<sub>trans</sub> for the reference structure. This is not automatically done by CREST.


Concering the *C*<sub>p</sub> I have to think again, it might be that its equivalent to the  `δSrrho` term is missing in the printout.

**Comment by cassguff** [comment]
Oh I see. That is a very helpful explanation, thank you.

Looking at the GFN2-xTB results, the S(total) I got was 15.1 cal/molK.
GFN-FF got an S(total) of 14.71 cal/molK. This still seems somewhat low.
It's the S(total) printed at the very end. Is that correct?

The value it gives for Cp(total) in that same table is the same value given
in the temperature dependence table for the conformational Cp(T) at 300K,
which still seems low as well. Is there a term I must manually add in?

**Comment by pprcht** [comment]
For the GFN-FF calculation the value is perfectly fine. GFN2-xTB is a bit low, but still plausible. As explained in the paper, the whole sampling process is not fully deterministic (hence also the thing with the extrapolation). For the drug molecules we ran the procedure a few times and took the average entropy, that's where the error bars in the figure come from.

Concerning *C*<sub>p</sub>, I looked at the code. The final value `Cp(total)`, which is the same as in the longer table, is the equivalent to the *configurational* term (Eq. 13). There is neither extrapolation, nor an equivalent to the `δSrrho` for  *C*<sub>p</sub> or the enthalpy. I mean to remember choosing so because the respective terms depend on the derivatives of the partition function, rather than directly on it as does the entropy. Meaning the `δ` equivalents are tiny. As with the entropy you need to add `Cp(total)` to your DFT reference to obtain the absolute value.
Now, this doesn't explain to me why the value seems to be a bit low. But technically everything works as intended.
