### ISSUE TITLE
GFN2-xTB always used for optimization in QCG 

### ISSUE THREAD

**Issue by dsvatunek** [crest-lab/crest#221]
GFN2-xTB does not work for the 1,2,4,5-tetrazines I work with, as it incorrectly predicts a non-planar structure. 

GFN1-xTB predicts the correct structure so I would like to use it for optimization. However, using the flags `--gfn1` and `--enslvl gfn1` I still get for the grow part

`  Final gfn2 optimization`

and for the ensemble part

````
GFN2-xTB optimization
 --------------------------------------------
 Ensemble optimization with normal thresholds
````
 
 Is there an option to set all geometry optimization to GFN1-xTB? This would be very helpful.

**Comment by cplett** [comment]
Thank you for bringing this up. Currently, there is no option to perform all steps with GFN1-xTB, but this would be definitely a nice-to-have feature. I will update the source code soon with a QCG version where this is possible.

**Comment by dsvatunek** [comment]
Thanks for looking into this! Looking forward to it.

**Comment by cplett** [comment]
With commit #224, no final GFN2-xTB geometry optimization will be done if GFN1-xTB or GFN-FF is selected. I hope this solves your issue.
