### ISSUE TITLE
Implemnetation of CPCM-X

### ISSUE THREAD

**Issue by moabe84** [crest-lab/crest#222]
Hi Philipp,
I came across [this recent paper](https://pubs.acs.org/doi/abs/10.1021/acs.jpca.3c04382) from the Grimme's group that introduces implementation of the CPCM-X solvation method. I'm wondering if it's already available in the package. It says it can be invoked by using the command line keyword “--cpcmx”.  

Thanks,
Mostafa

**Comment by pprcht** [comment]
It is not. The keyword described in the paper is for `xtb` only, so far.
