### ISSUE TITLE
how to tell how long it will take? 

### ISSUE THREAD

**Issue by jouteurestaque** [crest-lab/crest#225]
Hello
I have for the first time perform a CREST on a very big flexible molecule (lipid derivative), it is running for more that 8 dyas on a 36 CPU clusters.
is There any chances I can tell how low it is supposed to last? Seems I am on a loop cause it is finding lower conformers all the iteration time...

and anyhow can it be restart somehow?? I don't think I ever found that?
can it be parallelized with several nodes? can't retrieve that either//

cheers

[crestsolong.zip](https://github.com/crest-lab/crest/files/12576247/crestsolong.zip)

**Comment by pprcht** [comment]
No, there is no way to tell *a priori* how long the calculation will take. With the system size and flexibility you are looking at it is not unexpected to have quite long runtimes. If you are using  a queuing system like slurm, keep in mind that CREST (at least in the current main version) produces a lot of I/O that can slow down the calculation if you are not running it on the node scratch.

There is no dedicated restart function so far (I'm working on it) but you can use the intermediate ensembles of course. Likewise, multi-node parallelization is not available, the code is not (yet) optimized for MPI.

**Comment by jouteurestaque** [comment]
Thank you Philipp
yeah it is on the scratch indeed.
ok I will pray it finishes before the 20th..thak you so muck
