### ISSUE TITLE
output files meaning

### ISSUE THREAD

**Issue by cassguff** [crest-lab/crest#227]
Do you have documentation somewhere for what each of the output files mean? In particular, I would like to know the difference between cre_degen and cre_degen2, as well as what cre_members is.

**Comment by pprcht** [comment]
We have some description of [input file formats](https://crest-lab.github.io/crest-docs/page/documentation/coords.html), but not for output files. Would be a good idea actually.
cre_degen and cre_degen2 store the same type of information, i.e. the number of rotamers per conformer, but are written under different condition.
cre_members is used for internal bookkeeping while building crest_conformers.xyz from crest_rotamers.xyz.
