### ISSUE TITLE
Bus error in conformational search

### ISSUE THREAD

**Issue by camKD** [crest-lab/crest#229]
Hello,

I have been having a problem with the conformational search in CREST 2.11.2. I am running on an HPC system. These are the relevant jobscript settings and CREST command:

```
#SBATCH -n 16
#SBATCH --nodes=1
export OMP_NUM_THREADS=$NSLOTS,1
export OMP_STACKSIZE=4G

crest $path_to_file --gfn2 --esort --ewin $energy  --T 16 >$structure.crest.log
```

Here is the error from the workload manager:

```
Change the name of the structure variable!!!
forrtl: warning (768): Internal file write-to-self; undefined results
abnormal termination of xtb
forrtl: warning (768): Internal file write-to-self; undefined results
normal termination of xtb
/var/lib/slurm/slurmd/job9814588/slurm_script: line 60: 788220 Bus error               (core dumped) crest $path_to_file --gfn2 --esort --ewin $energy --T 16 > $structure.crest.log
```

I get the forrtl warnings on my other successful runs too, so it's just the last line. I've tried giving the job more memory but it doesn't seem to help. This is the structure:

39
 energy: -79.160423784689 gnorm: 0.000047084974 xtb: 6.4.1 (afa7bdf)
S        -3.22242898358865    1.86624549650045    0.95973111981941
O         1.11843802803039   -0.41217482748083   -0.98762595314828
O         0.36514548550572   -0.19143049017688    1.71780675309701
O         4.94273512013157   -0.56379004198131    1.87926752628556
O        -3.69911221284608    1.01370438789525   -0.30187337403880
O         4.82623331307138    2.40089550006547   -1.83366598808825
O        -5.09065147490553   -1.23464480555800   -0.93672927698338
O        -4.56736166641246    2.67185891274995    1.17878560161166
O        -2.22557022084221    2.79894937390847    0.56302321308162
O        -3.01770240116444    1.02801889905010    2.07842090743624
C         0.85011214358979   -1.41546910593597    1.22977461856343
C         0.52437223487039   -1.47966965192930   -0.27786599551148
C         2.36693881321128   -1.53892982640853    1.39070342747317
C         3.02866579204084   -0.52618778896916    0.49774753565134
C        -0.96482434864484   -1.42953248479404   -0.49991231503740
C         2.35554275248836   -0.00732460474334   -0.60363772198316
C         4.30568949794638   -0.04523170612150    0.79051126864388
C        -1.64305848903824   -0.22797908686279   -0.33331649025262
C         2.94574824382146    0.97795891568245   -1.39210404593473
C        -1.67994900357658   -2.57140247775845   -0.82496647042147
C         4.90222969896796    0.92417678179862    0.00239018028617
C         4.21316303694094    1.44266475456952   -1.08845883330636
C        -3.01439022362505   -0.17328367767369   -0.48044116423360
C        -3.05358914098809   -2.51641071891780   -0.98124046761686
C        -3.74398917991484   -1.32394604149622   -0.80449034171914
H         0.34013550457740   -2.26000473644541    1.72239503915514
H         0.92327186230684   -2.43209495498307   -0.66411142039108
H         2.68926192435478   -2.55263264256348    1.13669053790332
H         2.66126814897895   -1.35198202458989    2.42598655908830
H        -1.10632364634983    0.66863340249551   -0.07221505566063
H         2.39067157616170    1.36712698018965   -2.23181831730131
H        -1.16851805010017   -3.51304862077421   -0.95782291406399
H         0.55890521769772   -0.11971326587921    2.65763898405348
H         5.89114501400674    1.29539400359057    0.22453276350734
H        -3.60476768540061   -3.41245274385650   -1.23304712234879
H         5.80254688162243   -0.13673640719272    1.97291613121245
H         4.23305126875789    2.68433140241295   -2.53962691476812
H        -5.45390682525277   -2.10239201676253   -1.15588838978902
H        -4.61832800643456    3.39570593894523    0.55263640572912

These same settings work fine for two other similar structures, the main difference being that this one has a sulfur atom. Could that be the problem? Perhaps that's too simple. Any suggestions would be much appreciated!!!!

**Comment by pprcht** [comment]
The actual error seems to come from `xtb` rather than CREST according to the printout you gave.
It doesn't give much clues what went wrong though.
Could you update the CREST version? If the error comes from some IO communication issue between `xtb` and CREST this might fix it already.
