### ISSUE TITLE
How to restart an unfinished job?

### ISSUE THREAD

**Issue by abhijitrkjr** [crest-lab/crest#230]
Hi, I am running a conformer search for a big metal complex. Unfortunately, the job takes more time than we can use in our hpc. So, the job gets terminated while the conformer search is still going on. Can I restart the conformer search process who where it had stopped?

**Comment by pprcht** [comment]
Hello, see e.g. issues #14  #212, it is addressed there. Dedicated restart functions for the conformational sampling will be available from version 3.0 onwards, but there is no change to the status quo with the current version.
