### ISSUE TITLE
Error message when trying to reproduce an example: invalid pointer 

### ISSUE THREAD

**Issue by gosiao** [crest-lab/crest#233]
Dear Colleagues,

I'm trying to reproduce an example https://crest-lab.github.io/crest-docs/page/examples/qcg/example_1.html
using crest distribution via conda

```
       Version 2.12,   Thu 19. Mai 16:32:32 CEST 2022
  Using the xTB program. Compatible with xTB version 6.4.0
```

First, I got this error message:

```
ERROR STOP No xtb-IFF found. This is currently required for QCG and available at https:/github.com/grimme-lab/xtbiff/releases/tag/v1.1
```

so I installed `xtbiff` and restarted an example;
but this time I got this error message:

``` Solute geometry
munmap_chunk(): invalid pointer

Program received signal SIGABRT: Process abort signal.

Backtrace for this error:
#0  0x14fc21e9751f in ???
	at ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
#1  0x14fc21eeb9fc in __pthread_kill_implementation
	at ./nptl/pthread_kill.c:44
#2  0x14fc21eeb9fc in __pthread_kill_internal
	at ./nptl/pthread_kill.c:78
#3  0x14fc21eeb9fc in __GI___pthread_kill
	at ./nptl/pthread_kill.c:89
#4  0x14fc21e97475 in __GI_raise
	at ../sysdeps/posix/raise.c:26
#5  0x14fc21e7d7f2 in __GI_abort
	at ./stdlib/abort.c:79
#6  0x14fc21ede675 in __libc_message
	at ../sysdeps/posix/libc_fatal.c:155
#7  0x14fc21ef5cfb in malloc_printerr
	at ./malloc/malloc.c:5664
#8  0x14fc21ef5fdb in munmap_chunk
	at ./malloc/malloc.c:3060
#9  0x14fc21efa499 in __GI___libc_free
```

i also tried to run this example with crest installed from sources and as a pre-build executable, but I always end up with some errors, and cannot reproduce this example.

I'm using gfortran and gcc (11.4.0) and `ulimit -s unlimited`

I'll greatly appreciate your help, thank you!

best wishes,
Gosia

**Comment by cplett** [comment]
Hi,
QCG had a few bugs in crest version 2.12. I would therefore recommend the current continous release of crest.
There, the _xtbiff_ program was replaced by the aISS docking algorithm of _xtb_. However, this requires at least _xtb_ version 6.6. If you want to use the old _xtbiff_ program with the continous release of crest, the "--xtbiff" flag has to be provided. Maybe, this caused the error of the installation from source.
