### ISSUE TITLE
--notopo option in CREGEN sorting not working 

### ISSUE THREAD

**Issue by vpostils** [crest-lab/crest#234]
Dear CREST contributors,

    I am using Version 2.11 of CREST and trying to sort the created conformers using the CREGEN functionality alone because there are undoubtedly too many conformers for my post-processing. Despite increasing Ethr, RMSthr, and Bthr, I still have too many conformers and I wanted to exclude some atoms within a second sorting. 

    The program is not recognizing the --notopo flag neither the <atomlist>. See the output below.
    I have tried different <atomlist> formats (with only "," or using also "-"), and changing the ordering of the --cregen options. The program is not recognizing the --notopo flag in all of them and it provides me the same result as the equivalent calculation without the --notopo option. 

________________________________

       ==============================================
       |                                            |
       |                 C R E S T                  |
       |                                            |
       |  Conformer-Rotamer Ensemble Sampling Tool  |
       |          based on the GFN methods          |
       |             P.Pracht, S.Grimme             |
       |          Universitaet Bonn, MCTC           |
       ==============================================
       Version 2.11, Mon 1. Feb 10:36:12 CEST 2021
  Using the xTB program. Compatible with xTB version 6.4.0

   Cite work conducted with this code as

   P. Pracht, F. Bohle, S. Grimme, PCCP, 2020, 22, 7169-7192.

   and  S. Grimme, JCTC, 2019, 15, 2847-2862.

   with help from:
   F.Bohle, S.Ehlert, S.Grimme, P.Pracht

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

 Command line input:
 > crest struc.xyz --cregen crest_ensemble.xyz --notopo 18,19,20,21,22,23,24,25,26,27,28,29,31,32,33,34,35,36,37,38,39,40,41,42,79,80,81,82,83,84,86,87,88,89,90,91,94,95,96,97,98,99,102,103,104,105,106,107 --rthr 0.700 --ethr 0.20 --bthr 0.02 -T 2

  --cregen : CREGEN standalone usage. Sorting file <crest_ensemble.xyz>
  --rthr 0.700
  --ethr 0.20
  --bthr 0.02
  -T 2 (CPUs/Threads selected)
 Using only the cregen sorting routine.
 input  file name : crest_ensemble.xyz
 output file name : crest_ensemble.xyz.sorted
 number of atoms                :   120
 number of points on xyz files  :   8260
 RMSD threshold                 :   0.7000
 Bconst threshold               :   0.0200
 population threshold           :   0.0500
 conformer energy window  /kcal :   6.0000
 # fragment in coord            :     1
 number of reliable points      :  8260
 reference state Etot :  -155.126354610000
 running RMSDs...
 done.
_______________________________

Could you provide me some insight about what could be happening or if I am doing something wrong? I cannot find a solution in the documentation. 

Thank you.

All the best,

Verònica.

**Comment by pprcht** [comment]
The program version (2.11) simply doesn't know about these things. 
Upgrade to a newer version, that is the only reasonable "fix".
