### ISSUE TITLE
Does --cbonds command boost the calculation speed?

### ISSUE THREAD

**Issue by OkKakao** [crest-lab/crest#236]
Hi.

I'm using crest for molecular cluster structural exploration.

My system consists of roughly 600 atoms, which contains 4 cyclodextrin molecules.

Since it takes at least two hours for tight energy minimization with gfn2-xtb, I'm trying to used gfn-ff for the search.

However, gfn-ff predicts squeezed cyclodextrin strucutures, and still the calculation is too slow.

This is why I want to try --cbonds option.

Does confining the molecular structure with --cbonds command increases the speed of the caculation?

**Comment by OkKakao** [comment]
Then It would be better to try constrained run for such big system.
Can I constrain bond angles as well as bond lengths?
I want to perform crest run with maintaining the structure of the molecules.

**Comment by pprcht** [comment]
Yes, you can constrain anything you like. It might be complicated with several independent molecules though.
You can read up on the general constraining here https://crest-lab.github.io/crest-docs/page/examples/example_4.html#fixing-of-entire-substructure-parts
