### ISSUE TITLE
cannot reproduce official QCG examples

### ISSUE THREAD

**Issue by gosiao** [crest-lab/crest#239]
Hello,

I'm trying to reproduce CREST and QCG examples from the official website (https://crest-lab.github.io/crest-docs/page/examples), but I cannot reproduce all outputs.

For instance, QCG example 2 (https://crest-lab.github.io/crest-docs/page/examples/qcg/example_2.html) stops at a step of growing the cluster, without any error message. The last lines of output are:

```
  =========================================
  |   quantum cluster growth: GROW        |
  =========================================

 Solute:
       unit ellipsoid axis a,b,c     :   0.408   0.306   0.286
 Solvent:
       unit ellipsoid axis a,b,c     :   0.386   0.322   0.292

  solvent anisotropy            :     1.133
  solute anisotropy             :     1.169
  roff inner wall               :     1.388
  solute max dist               :    17.496
  solvent max dist              :     7.284
  inner unit axis               :     0.487     0.274     0.239
  inner ellipsoid/Bohr          :    14.889     8.363     7.291
  scaling factor outer ellipsoid:     1.000
  outer ellipsoid/Bohr          :    14.686    11.006    10.277

  Size       E        De       Detot      Density     Eatom    av. R  Rlast   Volume    Opt
            [Eh]    [kcal]     [kcal]     [u/Å^3]     [kcal]   [bohr] [bohr] [bohr^3]
```

which is only at ~15% of an expected output file.

I'm using CREST installation on an HPC cluster with intel 2021; the job is run sequentially, as in the example:
`crest benzoic_acid.xyz --qcg water.xyz --nsolv 3 --T 1 --ensemble --mdtime 50 --alpb water --wscal 1.0 --nofix `

CREST version: 2.12

Are the examples listed on the website updated? How can I further inspect this issue? Thanks!

**Comment by cplett** [comment]
Hi,
It seems that there is some kind of error arising that is somehow suppressed. Maybe you can add something like "2> error.out" at the end of the command line call. This should write the error to the "error.out" file. 
Moreover, I guess that this is a segmentation fault which was a problem of QCG in version 2.12. If possible, you may try the current continous-release version (https://github.com/crest-lab/crest/releases) that already contains a lot of bug fixes.

**Comment by gosiao** [comment]
Hi @cplett 
Thank you for a prompt reply!

I am actually redirecting it to a "log" file, but this does not produce anything more... Specifically, i'm running the test as
` crest benzoic_acid.xyz --qcg water.xyz --nsolv 3 --T 1 --ensemble --mdtime 50 --alpb water --wscal 1.0 --nofix >log`.

I'm using version `02da018` in the test, which is the one you mentioned.

**Comment by gosiao** [comment]
Hi again, @cplett

I've just rerun the example with redirecting the stderr to a file as you suggested (somehow, i missed that while reading your suggestion yesterday...). It gave only 1 line: `error while reading input coordinates`.
 
All input xyz files (`water.xyz` and `bacillaene.xyz`) are in the directory; there are also `solvent.xyz` and `solute.xyz` files created in this directory, as well as subdirectories `grow` (with an empty `qcg_grow.xyz` file ) and `qcg_tmp` (with 3 subdirectories)..

I saw this error is produced by `src/strucreader.f90` and looked inside - could it be an issue with paths/filenames?

Thanks a lot for your help!

**Comment by cplett** [comment]
Hi,
This was a bug in version 2.12 if I remember correctly. Did you test a version build with the current source code?
Otherwise, crest version 2.11.2 should still work, but requires the _xtbiff_.

**Comment by gosiao** [comment]
Hi @cplett 

Thanks a lot for your message!
I'm using version `02da018` in the test, which I believe is the most recent one on master...

**Comment by cplett** [comment]
Hi,
I checked for this and it seems that the latest [Continous release version](https://github.com/crest-lab/crest/releases/tag/latest) shows this error. Thank you very much for the report.
Maybe there is a compatibility problem with a certain compiler. Did you use a self-compiled version of the source code? If yes, it would be great if you could tell me which compiler you used so that I can fix it.

**Comment by gosiao** [comment]
Hi @cplett 

Thanks for your message and for checking this out!
I tested this with a compilation kindly provided by my colleague on the HPC side - there, it was done with intel 2021.2.0.
Earlier, I tested this with my own compilation on my laptop using gfortran, but there i had other issues (#233).

In both cases (intel and gfortran), I also tested the code available through conda; same mistakes.

**Comment by cplett** [comment]
Hi,
Thank you for the information. I will try to reproduce the problem so that I can fix this.
