### ISSUE TITLE
Total Energy of cluster not found

### ISSUE THREAD

**Issue by wissamhelal** [crest-lab/crest#241]
Dear Colleagues,

I use CREST Version 2.12. Using the xTB program. Compatible with xTB version 6.4.0

In a qcg calculation, I have asked to grow a cluster of 100 water molecules around a cucurbituril guest host complex. I ran the following command: 

crest solute.xyz --qcg water.xyz --nsolv 100 --gfnff --T 4 --alpb water --nofix > output.out

I have tried with "--nofix" and with "--fixsolute", changed the solvation model to GBSA, and tried slightly different geometries of the solvent and solute. In all trials, the calculation stopped at step size 63 writing the following at the end of the output file:

   62  -600.291629  -13.33    -766.17       1.403    -32.603     14.7  16.5   19424.9   normal
   63  -605.383695  -13.64    -779.82       1.402    -32.735     14.7  16.1   19582.7   normal
 Cluster energy not found
   Interaction Energy positiv, increasing outer wall pot by 5 %
 New scaling factor 0.88
 Cluster energy not found
   Interaction Energy positiv, increasing outer wall pot by 5 %
 New scaling factor 0.93
 Cluster energy not found
   Interaction Energy positiv, increasing outer wall pot by 5 %
 New scaling factor 0.97
 Cluster energy not found
   Interaction Energy positiv, increasing outer wall pot by 5 %
 New scaling factor 1.00
 Cluster energy not found
 Total Energy of cluster not found.
   64     0.000000 *******   ********       1.400      0.000     14.7  16.7   19759.7   normal

I really appreciate you help

Wissam

**Comment by cplett** [comment]
Hi,
This is probably a problem with the wall potentials. I'm currently working on a solution for this, but a quick fix might be the manual adjustment of the potentials with the _--wscal <real>_ keyword. I suggest trying out a number larger than 1.0 like 1.5.

**Comment by wissamhelal** [comment]
Thanks for the reply. I have systematically tried different scaling factors (through wscal): 1.0, 1.2, 1.4, 1.5, 1.6, 1.7, 1.8, and 2.0. Non of them worked! Although a higher step size was reached with increasing the scaling factor (e.g. 75 for wscal 2.0), but did not reached the desired 100 or higher.

**Comment by wissamhelal** [comment]
Thanks for the reply. I have systematically tried different scaling factors (through wscal): 1.0, 1.2, 1.4, 1.5, 1.6, 1.7, 1.8, and 2.0. Non of them worked! Although a higher step size was reached with increasing the scaling factor (e.g. 75 for wscal 2.0), but did not reached the desired 100 or higher.

Thanks for the assistance

Wissam
________________________________

**Comment by cplett** [comment]
Thank you for trying out and for the report. I'm working on fixing that problem for the next release and I will upload the fix as soon as I have it.
