### ISSUE TITLE
How do I modify the topology?

### ISSUE THREAD

**Issue by shoubhikraj** [crest-lab/crest#244]
Hi,

I have been using CREST to generate conformers of a organometallic complex. The problem is that for the complexes, the topology that is generated by CREST contains some bonds which are not needed during the conformer search. I want the metal catalyst part and the substrate parts of the complex to freely rotate between themselves, however, CREST attaches those two with bonds.

I have tried turning off the topology checking with `--notopo`, but it does not seem to help. I suspect it is the SHAKE used during MD that forces those bonds to not detach. If I turn off SHAKE as well, it works, but it also generates thousands of conformers, breaking many other bonds (which I don't need to break).

Is there any way to manually define the topology for a system? i.e. decide which atoms are bonded and which are not. Or is there a way to modify the default topology from CREST?

Many thanks.

**Comment by OkKakao** [comment]
I have the same issue...

Did you find the solution?

I tried split method which is embedded in xcontrol.
![image](https://github.com/crest-lab/crest/assets/101975748/f5a3e481-48c9-4182-b421-5e631cf17012)

It seems worked well when I checked xtbtopo.mol, but the output file remained the same.

The excess bonds were not removed...

**Comment by OkKakao** [comment]
> Hi,
> 
> I have been using CREST to generate conformers of a organometallic complex. The problem is that for the complexes, the topology that is generated by CREST contains some bonds which are not needed during the conformer search. I want the metal catalyst part and the substrate parts of the complex to freely rotate between themselves, however, CREST attaches those two with bonds.
> 
> I have tried turning off the topology checking with `--notopo`, but it does not seem to help. I suspect it is the SHAKE used during MD that forces those bonds to not detach. If I turn off SHAKE as well, it works, but it also generates thousands of conformers, breaking many other bonds (which I don't need to break).
> 
> Is there any way to manually define the topology for a system? i.e. decide which atoms are bonded and which are not. Or is there a way to modify the default topology from CREST?
> 
> Many thanks.

Did you tried --notopo option with atom specific option?

I tried this option

```--notopo Li,I
-notopo <x> : ignoring topology on 7 atoms (Li,I)```

I think this can be applied to nth atoms.

```--notopo 2,3,7-9```
