### ISSUE TITLE
memory problem

### ISSUE THREAD

**Issue by luissimon** [crest-lab/crest#248]
I have some problems possibly related to memory management when trying to use CREST (v2.12, with different XTB versions, both installed from binaries). Aparently, XTB works fine, but fails when it is called by CREST even for the first geometry optimization. The messages refers to memory management: 
*** glibc detected *** xtb: free(): invalid next size (normal): 0x0000000007c6bc30 ***
when run with -T=1, or: 
forrtl: severe (174): SIGSEGV, segmentation fault occurred
when run with -T=2
I also set: ulimit -s unlimited, exported: OMP_STACKSIZE= large amount of memory G, etc.

Funniest thing is that I have run CREST before without these issues on the same server. I think that I did not anythin "nasty" to the server... only upgraded some CUDA libraries in a different machine that shares some directories by NFS.

Any idea?

Thanks:

Luis

**Comment by luissimon** [comment]
an update... I removed the --zs keyword in the crest invocation and the message changed to:

*** glibc detected *** xtb: corrupted double-linked list: 0x0000000007e21630 ***

**Comment by luissimon** [comment]
Turn out that I have been able to launch calculations placing the initial xyz file in a directory... so I guess that in my home directory there is a file that sould be deleted (and maybe I do not have permissions to do that) or some error of this kind...

**Comment by pprcht** [comment]
Hm I don't know how this would be related to parallelization.
There could be multiple different things going on here. The best would be to try running your entire calculation within a fresh directory.
Changed libraries could have an impact on this, the safe way to avoid it is to build the program yourself on the machine you are running it on.
The glibc errors you posted suggest that they originate from xtb, not CREST, however.
