### ISSUE TITLE
CREST v3.0 Pre release SIGSEGV, segmentation fault occurred

### ISSUE THREAD

**Issue by Rintontin** [crest-lab/crest#252]
Hi
I am using crest Version 3.0pre, Sat Jan 20 21:44:12 UTC 2024
       commit (fafd635) compiled by 'runner@fv-az1423-259'
I tried to tautomerize a L-histidine molecule as a test and I got the following error.

manager@pc-1:~/programs/xtb$ crest test.xyz -tautomerize > test.out
forrtl: warning (768): Internal file write-to-self; undefined results
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
crest              00000000026244D0  Unknown               Unknown  Unknown
crest              000000000246193F  Unknown               Unknown  Unknown
crest              000000000241BB75  Unknown               Unknown  Unknown
crest              000000000241B8D7  Unknown               Unknown  Unknown
crest              0000000000619EE9  protens_                  485  tautomerize.f90
crest              000000000253265F  Unknown               Unknown  Unknown
crest              00000000025383C9  Unknown               Unknown  Unknown
crest              000000000258E246  Unknown               Unknown  Unknown
crest              0000000002592C5B  Unknown               Unknown  Unknown
crest              00000000024C4D1F  Unknown               Unknown  Unknown
crest              000000000061A28D  protens_                  500  tautomerize.f90
crest              00000000025481D3  Unknown               Unknown  Unknown
crest              00000000024FC12E  Unknown               Unknown  Unknown
crest              00000000024FB132  Unknown               Unknown  Unknown
crest              0000000002548E99  Unknown               Unknown  Unknown
crest              000000000261E709  Unknown               Unknown  Unknown
crest              00000000026AA4E3  Unknown               Unknown  Unknown

I am using the latest pre release version of xtb commit https://github.com/grimme-lab/xtb/commit/0fb151dceb19b8df9f6012789cf7d2dd6e4a6cd2

My operating system is Linux Ubuntu 22.04.3 LTS 64bit
AMD® Ryzen threadripper 2990wx 32-core processor × 64
Memory: 128.0 GiB
gfortrand and gcc version 11.4.0
Python 3.10.12

[test.zip](https://github.com/crest-lab/crest/files/14000222/test.zip)

**Comment by pprcht** [comment]
#253 should do it.
Please not that the protonation tools are one part of the code I have yet to update to the new calculation interfaces.

**Comment by JayTheDog** [comment]
Hey, from what I see the protonation tool still introduces some errors (in this case via calling it with `--tautomerize`:
  ```
      __________________________________________
       |                                          |
       |     automated tautomerization script     |
       |__________________________________________|
  Universitaet Bonn, MCTC
  P.Pracht, Wed 28. Nov 13:11:52 CEST 2018
 
 Cite as:
 P.Pracht, R.Wilcken, A.Udvarhelyi, S.Rodde, S.Grimme
 JCAMD, 2018, 32, 1139-1149.
 
 
******************************************************************************************
**                   P R O T O N A T I O N   C Y C L E     1 of 2                       **
******************************************************************************************
 
forrtl: severe (124): Invalid command supplied to EXECUTE_COMMAND_LINE
Image              PC                Routine            Line        Source             
crest              00000000006E9E3D  iomod_mp_command_        1018  iomod.F90
crest              00000000005FBEC7  xtblmo_                   226  protonate.f90
crest              000000000062199E  protsmall_                225  tautomerize.f90
crest              0000000000617C5E  tautomerize_               88  tautomerize.f90
crest              0000000000403CC7  MAIN__                    151  crest_main.f90
crest              000000000040334D  Unknown               Unknown  Unknown
crest              00000000026279A0  Unknown               Unknown  Unknown
crest              000000000040322E  Unknown               Unknown  Unknown
```

Also there seems to be a typo in line 572 of `src/legacy_algos/tautomerize.f90`. 

Thanks for looking into it!
