### ISSUE TITLE
NCI - how to study an ion -water cluster?

### ISSUE THREAD

**Issue by johnwkeller54** [crest-lab/crest#267]
I started "crest --nci" with an sdf file with a non-zero formal charge on O (OH- ion), but this was ignored and an OH radical-water cluster was obtained. How do you specify, or indeed, can you specify, and ionic state?

**Comment by pprcht** [comment]
with ``--chrg -1``

**Comment by johnwkeller54** [comment]
Philipp Pracht says " with --chrg -1 " parameter. Thanks!

**Comment by johnwkeller54** [comment]
ok
