### ISSUE TITLE
Support compiling code under Windows

### ISSUE THREAD

**Issue by kartlee** [crest-lab/crest#276]
The codebase doesn't compile under Windows, and while trying to see how far it goes with Visual Studio 2019 + Intel ifort 2022, I observed the following -

-    I had to set the following in main project of crest, and its subprojects 

           `if fc_id == 'intel-cl'
               add_project_arguments(
                   '-fpp',
                   language: 'fortran',
               )
           endif`

- At at the final stage while linking crest, I see the following 
          `[stdout] "xilink.exe"  /MACHINE:x64 /OUT:crest.exe crest.exe.p/src_crest_main.f90.obj "/LIBPATH:E:/software/lib/Windows-common/ifort_2022.0.0/compiler/lib/intel64" "/LIBPATH:E:/software/lib/Windows-common/ifort_2017.1.040/mkl/lib/intel64" "/nologo" "/OPT:REF" "libcrest.a" "subprojects/tblite/libtblite.a" "subprojects/mctc-lib/libmctc-lib.a" "subprojects/dftd4/libdftd4.a" "subprojects/multicharge/libmulticharge.a" "subprojects/s-dftd3/libs-dftd3.a" "subprojects/toml-f/libtoml-f.a" "subprojects/gfn0/libgfn0.a" "subprojects/gfnff/libgfnff.a" "subprojects/lwoniom/liblwoniom.a" "mkl_rt.lib" "mkl_rt.lib" "mkl_rt.lib" "mkl_rt.lib" "mkl_rt.lib" "mkl_rt.lib" "mkl_rt.lib" "mkl_rt.lib" "mkl_rt.lib" "mkl_rt.lib" "mkl_rt.lib" "mkl_rt.lib" "mkl_rt.lib" "mkl_rt.lib" "mkl_rt.lib" "mkl_rt.lib" "mkl_rt.lib" "mkl_rt.lib" "mkl_rt.lib" "mkl_rt.lib" "mkl_rt.lib" "mkl_rt.lib" "mkl_rt.lib" "/SUBSYSTEM:CONSOLE"
          [stdout] libcrest.a(src_iomod.F90.obj) : error LNK2019: unresolved external symbol setenv referenced in function IOMOD_mp_SETENV_STRING
          [stdout] libcrest.a(src_iomod.F90.obj) : error LNK2019: unresolved external symbol symlink referenced in function IOMOD_mp_SYLNK`

Above posix symbols are not available in windows vc compiler, and so those bindings needs to be fixed.

Would it be possible to check at your end compiling under windows, and see if crest works?

**Comment by pprcht** [comment]
We don't support or maintain a windows build at the moment. I don't think this will change anytime soon.
Since some functions like QCG run shell commands as a subprocess, I'm pretty sure it wouldn't run without issues anyways.

Furthermore, I started moving away from the meson build system a bit and focus more on CMake.
