### ISSUE TITLE
Patches to compile 3.0pre for unix platforms

### ISSUE THREAD

**Issue by kartlee** [crest-lab/crest#277]
I had to apply the following patches to get the source compiled for linux and darwin.  Here are the comments about the patch -
   - The lapack option was required to pass from main to subprojects as la_backend was not accepeted in subprojects.
   - Had to suppress passing --allow-multiple-definition to ld in mac, as it was being thrown as unrecognized option.
   - There was no option to set a preferred omp library, so had to set a global link argument for it.

Please review and let me know your comments.

[crest-lwoniom.patch](https://github.com/crest-lab/crest/files/14727731/crest-lwoniom.patch)
[crest.patch](https://github.com/crest-lab/crest/files/14727732/crest.patch)

**Comment by pprcht** [comment]
As mentioned in #276, I am currently moving away a bit from the meson build and focus more on CMake.
The meson build is somewhat specialized, and if you want to adjust it with patches for a specific OS or build types, that is certainly fine. 

If you experience similar issues with CMake, please let us know, I think these are more worth fixing.
