### ISSUE TITLE
--constrain does not create file

### ISSUE THREAD

**Issue by cassguff** [crest-lab/crest#279]
I tried creating the constraints input file by using the "--constrain <atomlist>" keyword. It runs and says "<.xcontrol.sample> written. exit." But I do not see any new file created. Is this a bug? Or is this file created in a different place than the current directory? I can't find it.

**Comment by pprcht** [comment]
It creates it, but all files starting with "." are hidden files by default on unix systems.  You should be able to open it from the command line.
