### ISSUE TITLE
Tautomerism screening with gfnff

### ISSUE THREAD

**Issue by ryanpedersonterray** [crest-lab/crest#282]
I can't seem to get this example (https://crest-lab.github.io/crest-docs/page/examples/example_5.html#tautomerism-screening) to work with `--gfnff` or `--gfn2//gfnff`. Is it supported?

**Comment by pprcht** [comment]
No, they are unfortunately not supported. All the runtypes working with protonation require LMOs, and thus need a xTB calculation.

**Comment by ryanpedersonterray** [comment]
I see, thanks!
