### ISSUE TITLE
QCG failed with Hexane as solute

### ISSUE THREAD

**Issue by ik160** [crest-lab/crest#296]
I attempted QCG calculations for various hydrocarbons, but was unable to calculate for hexane as solute. I was able to calculate without any problems from C1 to C5, and C7.  
When I look at the results, the ellipsoid axis of the solute is all NaN, and I think this might be the cause. Is there a way to deal with this? Please advise.

crest version is 3.0.
xtb version is 6.7.0.
xtbiff version is 1.1.

command
$ crest hexane. xyz - qcg hexane. xyz - gfnff - xtbiff

**Comment by pprcht** [comment]
this seems to have been a proper bug, should be fixed with #300 and the [continuous release](https://github.com/crest-lab/crest/releases/tag/latest)
thanks!

**Comment by pprcht** [comment]
I'm closing the issue for now.
