### ISSUE TITLE
Crest 3 QCG, final xTB optimisations not using the available cores

### ISSUE THREAD

**Issue by andrewtarzia** [crest-lab/crest#297]
As in title, a QCG run seems to be hanging after adding the requested number of solvents, but looking at htop I see the following command is running:

`xtb cluster.xyz --gfn2 --opt best.xyz best_after_gen.xyz  cluster.coord cluster.xyz cluster_cavity.coord final_structures.xyz optimized_structures.xyz solute solute_cavity.cood solute_cut.cood .........`

As I understand, this is the final xtb optimisation of `cluster.xyz`, right? However, it seems to only be using 1 thread. Is there a way to change this? 

My crest version: `Version 3.0, Sat Apr  6 18:06:37 UTC 2024 commit (d321183) compiled by 'runner@fv-az778-216'`

Crest command: `crest input_solute.xyz --qcg input_solvent.xyz --nsolv 10 -xnam xtb --alpb water -chrg 0 -uhf 0 --gfn2 -T 6 --optlev crude --nopreopt --fixsolute -I det_control.in`

**Comment by andrewtarzia** [comment]
An alternative option is to turn off this final optimisation, which I would actually prefer. Is that possible?

**Comment by andrewtarzia** [comment]
Hey @pprcht , thank you for this! `--no_final_opt_gfn2` seems to avoid this issue. However, `cluster_optimized.xyz` is still written to file and seems to be very slightly different to `cluster.xyz`. Is that expected?

**Comment by pprcht** [comment]
From my understanding of the code, yes, that seems to be normal. @cplett is the author and maintainer of QCG.
What I read from the routine is that `cluster.xyz` is put forth for one final optimization to produce `cluster_optimized.xyz`. Even when `cluster.xyz` is a minimum already, the optimization will take one or two tiny steps. My guess is that's what you're seeing.

Have you by any chance checked if #300 also resolves your issue #294?

**Comment by andrewtarzia** [comment]
Ok, thank you again! I will update on #294  in that conversation.

Andrew
