### ISSUE TITLE
Understanding final solvation free energy calculation with QCG 

### ISSUE THREAD

**Issue by moabe84** [crest-lab/crest#299]
Hi Philipp,
I've conducted solvation free energy calculations with QCG and would like to understand how the final solvation free energy, reported in the "result.dat" file, is calculated. I understand that:

1) The free energy (G(T)) of the solute-solvent for all selected ensembles (based on the "nclus" keyword which is 5 in my calculations) is reported in the "solute_cluster.dat" file.
2) The free energy of the solvent for all selected ensembles is reported in the "solvent_cluster.dat" file.

The part that I don't fully understand is the "solute.dat" file. It's supposed to represent the G(T) for the solute in the gas phase. However, I'm puzzled as to why the values are very different from each other and how they are calculated. For example, for a given molecule:
277.15     92.79     35.83     43.68    225.78

Some clarification would be greatly appreciated.

Thanks,
Mostafa

**Comment by pprcht** [comment]
QCG is @cplett mostly, maybe he has a quick answer. I would need to look it up as well

**Comment by moabe84** [comment]
I think I've uncovered the meaning behind those values in the "solute.dat" file are:

H(T),  S(T)_vib,  S(T)_rot,  S(T)_tr,  G(T)

obtained from the gas phase calculations.
@cplett would you please confirm? 

Thanks,
Mostafa

**Comment by pprcht** [comment]
I had a look in code and think you are correct.

Related question, `solvent_cluster.dat` or `solute_cluster.dat` do have a header that says what the values are, right?
The `solute.dat` might be missing it because of an I/O typo.

**Comment by pprcht** [comment]
yeah... pretty sure the header didn't get printed. #301

**Comment by moabe84** [comment]
Thank you Philipp for the updates. I also suspected that the header is missing. Yes, the 'solvent_cluster.dat' and 'solute_cluster.dat' files have a header.

**Comment by pprcht** [comment]
I'm closing this issue for now.
