### ISSUE TITLE
Having trouble reproducing examples

### ISSUE THREAD

**Issue by GreenMeansForgive** [crest-lab/crest#305]
So when I was trying to reproduce 
https://crest-lab.github.io/crest-docs/page/examples/example_4.html#fixing-of-entire-substructure-parts
I'm currently using CREST 3.0.1, and executing the command returned 

```
Parsing xtb-type input file constraints.inp to set up calculators ...
coord file does not exist."
```

I tried adding -- legacy but still didn't work and got
```
  Initial geometry optimization failed!
  Please check your input.
```

I feel it has something to do with `reference=coord.ref` in `constraints.inp` b/c when I deleted this line the program seemed to be able to proceed, although I'm not certain this would yield the same sound results.

A similar problem occurred when reproducing another example of 
https://crest-lab.github.io/crest-docs/page/examples/publication/example_1.html#sampling-of-conformations-at-the-transition-state

Although this time I wasn't certain that I had done it correctly. I couldn't really understand what to put as input coordinates file. Was I supposed to provide two files with the same coordinates named "coord" and "coord.ref"? And the coord file wasn't supposed to have a suffix?

I'd really appreciated it if someone could solve this.

**Comment by pprcht** [comment]
You need a `coord.ref` as a reference, and a regular structure input file, which can be `coord` or some .xyz.
`coord.ref` can be a copy of your input (in coord-format) if you want to constrain the calculation to that.
