### ISSUE TITLE
Question in starting the xtb optimization

### ISSUE THREAD

**Issue by zhenghq0518** [crest-lab/crest#308]
Hello, I'm running a series of calculation with crest while encountering a common problem: the xtb optimizer in the start of the calculation cannot be started. My debug input is a ethene molecule and all inputs looks like this: 

sbatch script:

#!/bin/bash -l

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=40
#SBATCH --qos=lr_debug
#SBATCH --time=00:30:00
#SBATCH --partition=lr6
#SBATCH --account=pc_mp
#SBATCH --job-name=DLMcrest

crest ethene.xyz --T 40 --alpb hexane
mv crest_best.xyz ethene_crest_best.xyz

exit

First few lines of output:

 Command line input:
 > crest ethene.xyz --T 40 --alpb hexane

  --T 40 (CPUs/Threads selected)
  --alpb hexane : implicit solvation
 
 -------------------------
 xTB Geometry Optimization
 -------------------------
forrtl: severe (124): Invalid command supplied to EXECUTE_COMMAND_LINE
Image              PC                Routine            Line        Source             
crest              00000000014DE1BF  Unknown               Unknown  Unknown
crest              000000000067416B  xtbopt_                   184  confscript2_misc.f90
crest              0000000000698B84  MAIN__                    265  crest_main.f90
crest              0000000000402242  Unknown               Unknown  Unknown
crest              00000000017025D0  Unknown               Unknown  Unknown
crest              000000000040210E  Unknown               Unknown  Unknown
mv: cannot stat ‘crest_best.xyz’: No such file or directory

Would you please help me look into this? Thanks a lot!!

**Comment by pprcht** [comment]
While the "Invalid command supplied" suggests that there is an issue with finding the xtb binary, the line numbers given in the error report don't match up with the current source code.
May I ask which CREST version you are using? It doesn't seem to be a current one.

**Comment by zhenghq0518** [comment]
The version is 2.12
Meanwhile, I discovered that I need to activate my installed conda environment to make the script run smoothly, so this issue is I guess, solved? lol

**Comment by zhenghq0518** [comment]
I just found the xtb package in my conda environment~

**Comment by pprcht** [comment]
Yes you need to have xtb sourced and in your path for 2.12. It doesn't matter if it is from conda or installed separately
