### ISSUE TITLE
Running with constraints doesn't work if constraints file given as file path

### ISSUE THREAD

**Issue by cassguff** [crest-lab/crest#311]
Running crest with a constraints file is working fine for me as long as the constraints file is located in the current directory. For example `crest input.xyz --cinp constraints.inp`. But if I instead give a file path for the constraints file (for example `crest input.xyz --cinp file/constraints.inp`, it finds the file and reads it fine initially, but when it gets to "Starting a trial MTD to test settings" it throws errors forrtl: No such file or directory
forrtl: severe (29): file not found, unit -207

Am I doing something wrong here? The input file can be a file path just like that and still work, but the constraints file cannot. Is this stated somewhere in the documentation?

**Comment by pprcht** [comment]
This is not intentional, I will look into it. Was it a >3.0 CREST version?
For now you could copy the constraints file into the working directory before starting the program, if that seems to work.

**Comment by cassguff** [comment]
It is version 2.12. Perhaps a newer version won't have the problem. I can
also try that.
