### ISSUE TITLE
IMTD-GC segfaults on atoms and diatoms

### ISSUE THREAD

**Issue by jevandezande** [crest-lab/crest#320]
The imtd-gc method segfaults almost immediately if a geometry with a single atom is given. If a geometry with two atoms is given, it typically fails in the trial MTDs, otherwise it fails due to an "empty ensemble filecrest_rotamers.xyz" or segfaults in the Multilevel Ensemble Optimization.

Obviously, nobody should run these, but it would be preferable if CREST would failover to an optimization if 3 or fewer atoms were requested and fake that it ran imtd-gc by outputting the usual `crest_conformers.xyz`, `crest_best.xyz`, etc. files.

**Comment by pprcht** [comment]
It did that previously.
I will check if/where it needs to be reinstated.
Thanks for noticing.

**Comment by pprcht** [comment]
#322 should take care of it.
