### ISSUE TITLE
Crest single point and optimization segfault for GFN0 on atoms

### ISSUE THREAD

**Issue by jevandezande** [crest-lab/crest#321]
CREST segfaults for the following, where `geom.xyz` contains a single atom (tested multiple open and closed shell):

`crest geom.xyz --sp --gfn0`
`crest geom.xyz --optimize --gfn0`

But not if `gfnff`, `gfn1`, or `gfn2` are selected

Version 3.0.1

**Comment by pprcht** [comment]
I just [fixed](https://github.com/pprcht/gfn0/commit/584cec4b47da23bf3634ef0dd798a1639fcc5e47) it in the gfn0 project. Will update the corresponding submodule once I looked into #320.

**Comment by pprcht** [comment]
same here, #322 should implement the fix
