### ISSUE TITLE
different results from same settings

### ISSUE THREAD

**Issue by ismiek** [crest-lab/crest#324]
Hi everyone,

Is it normal to get three different results, i.e., three different numbers of conformers, when I run a CREST calculation (version 3.0.1) three times with the same settings and starting structures? I noticed in the output that the MTD simulations produce the same number of conformers, but the number of conformers differs after optimizations in all three cases.

Thank you in advance.

**Comment by pprcht** [comment]
Yes, the search is not deterministic due to the MD/MTD parts. Especially the number of high-lying conformers can differ. Only the lowest energy conformer(s) should be the same in the sampling limit.

**Comment by pprcht** [comment]
Because the MTD/MD runtime and snapshot dump frequency is the same. That means, while the same number of candidates are generated, since the MD/MTD can non-deterministically move to different regions of the PES, the candidates are not the same in different runs.

**Comment by ismiek** [comment]
Ah ok, thank you very much for your time and effort.
