### ISSUE TITLE
A problem with crest(msreact) and molbar

### ISSUE THREAD

**Issue by AndreySchadel** [crest-lab/crest#336]
Greeting developers and community members, i tried to make the example with benzene and find all possible high-energy conformations. It found all possible conformations and when tried to delete with molbar duplicates, it couldn't accessed the file 1temp.mb. I'm using WSL under windows 11 24H2.  The stdout where the problem occured is presented under:
 
```
 done.
 Detect fragments
 Remaining structures:        6982
 Calling molbar for sorting out duplicates by molbar
At line 592 of file /home/andreywslubuntu/CREST_src/src/msreact/msmod.f90
Fortran runtime error: Cannot open file '1temp.mb': No such file or directory

Error termination. Backtrace:
#0  0x7f60446f7960 in ???
#1  0x7f60446f84d9 in ???
#2  0x7f60446f910f in ???
#3  0x7f6044947ee6 in ???
#4  0x7f60449481dd in ???
#5  0x55ba4ff1b330 in __msmod_MOD_calcmolbar
        at /home/andreywslubuntu/CREST_src/src/msreact/msmod.f90:592
#6  0x55ba4ff1ba1d in __msmod_MOD_sortoutduplicates
        at /home/andreywslubuntu/CREST_src/src/msreact/msmod.f90:497
#7  0x55ba4ff146d0 in msreact_handler_
        at /home/andreywslubuntu/CREST_src/src/msreact/msreact.f90:103
#8  0x55ba4fbaada1 in crest
        at /home/andreywslubuntu/CREST_src/src/crest_main.f90:255
#9  0x55ba4fba8ebe in main
        at /home/andreywslubuntu/CREST_src/src/crest_main.f90:26
```

**Comment by pprcht** [comment]
@gorges97 may have an idea

**Comment by gorges97** [comment]
Does molbar work for you if you call it manually, e.g. with > molbar in.xyz ?  CREST only checks whether the binary is available and then tries to use it.

**Comment by AndreySchadel** [comment]
Yes, i checked it and got this:
`MolBar | 1.1.2 | C6H6 | 0 | -294 -120 -120 -14 -14 -3 74 140 140 514 514 743 | -180 0 0 360 360 540 | -55 -11 -10 -10 -7 -7 47 87 87 257 257 925 | 0`
I have installed molbar with pip as it is suggested by their developers.

**Comment by gorges97** [comment]
I could reproduce the error using WSL. It seems that the -s option that writes the (i)temp.mb doesn't work on WSL for multiple files, i.e., executing  molbar *temp.xyz -s > molbar.out somehow doesn't work here. So the issue lies here in molbar. However, I could rewrite the routine for the next release version to call molbar separately for each temp.xyz to make it stable also on WSL but I have to test first, if this doesn't have a large effect on the performance.

**Comment by AndreySchadel** [comment]
Thank you very much for the answer, i will try to install the program on a standalone version of linux. Although it is very strange, that WSL differ from it...

**Comment by AndreySchadel** [comment]
Greetings everyone, the problem is the same on Ubuntu 22.04 LTS. It seems that option -s doesn't work as well on standalone version. I opened topodir and tried to execute molbar *temp.xyz -T 12 -s > molbar.out, which got no results, however, when i tried molbar *temp.xyz -T 12 > molbar.out, it wrote me the standart output of molbar command, i will try to change in crest, that it supports running molbar without -s command and i will return the answer.
