### ISSUE TITLE
[QUESTION] - Meaning of `crest_dynamics.trj` Structures

### ISSUE THREAD

**Issue by coltonbh** [crest-lab/crest#343]
**Describe the issue**
I am trying to visualize and understand the metadynamics sampling of a CREST run. I am given the `crest_dynamics.trj` file by CREST. In my particular case it contains 357 frames (structures) and I can visualize the trajectory; however, I'm not sure what it means! 

During the run, CREST does 14 different metadynamics runs simultaneously and then does multiple iterations of these. What are these final 357 structures that are in the `crest_dynamics.trj` file? How are they related to the different MTD runs done by CREST over the course of the program execution? Does this `.trj` file represent the actual full sampling done by CREST or does it represent only some subset of the sampling? I think it must contain some small subset since often there were more structures to optimize than 357, so some of the sampled structures are clearly not included in this file. What structures _are_ included and is there any way to see the full sampling done by the CREST metadynamics?

**To Reproduce**
`input.toml`:
```sh
threads = 16
input = "structure.xyz"
runtype = "imtd-gc"

[calculation]
level = [
    { method = "gfn2", charge = -1, uhf = 0 },
]
```
`stdout` attached!
[stdout.txt](https://github.com/user-attachments/files/17021995/stdout.txt)

**Additional context**
Thanks so much for your help! :pray:

**Comment by pprcht** [comment]
The `crest_dynamics.trj` is simply all structures dumped by the a block of MDs or MTDs concatenated into a single file. It is used as a temporary file to collect structures and is overwritten several times. 
I think the surviving one is from the regular MD block before the GC step.

**Comment by coltonbh** [comment]
Got it. So this just happens to be the leftover file from the last MD block--it has no special significance, correct?

Is there any way to see/visualize all the sampling done by CREST? I'm trying to get an idea of how much initial conditions affect sampling and wanted to see if some of the structures I think should exist but aren't showing in the final conformers were actually sampled (but perhaps were at too high an energy) or if they were never sampled at all. Is there a good way to do this?

Thanks so much!

**Comment by pprcht** [comment]
No, it has no special significance.

You can use `-keepdir` to avoid deleting individual temporary trajectory files (which are collected into crest_dynamics.trj), however, the trajectory files may be overwritten during iterations.
