### ISSUE TITLE
Option imtd-mtd from the documentation not known (typo?)

### ISSUE THREAD

**Issue by codecollider** [crest-lab/crest#352]
I wanted to run a standard crest run for conformational sampling with this input file

```
# CREST 3 input file
input = "in.xyz"

#crest run
runtype='imtd-mtd'

threads = 16

[calculation]
elog="energies.log"

[[calculation.level]]
method = "gfn2"
#uhf = 0

#charge of molecule
chrg = 0
```

The option "imtd-mtd" I took from the documentation, i.e. "imtd-mtd - Standard conformational sampling algo based on metadynamics"

I get that error:

```
unrecognized ARGUMENT : imtd-mtd
ERROR STOP

Error termination. Backtrace:
```

I guess runtype='imtd-gc' is what I want to use, right? Maybe just a typo if I ddin´t misread the documentation .

**Comment by pprcht** [comment]
yes, thanks, you are correct.
I pushed the change, [see here](https://github.com/crest-lab/crest-docs/commit/d7b9992577ad67da131ea2e0cde1cda877bc5b52)
