### ISSUE TITLE
V2.11 - make install with cmake fails

### ISSUE THREAD

**Issue by grisuthedragon** [crest-lab/crest#36]
I am currently trying to install crest on our HPC system and the cmake configure-build-install procedure fails in the install step. I used the Intel 2018.1 Parallel Studio and CMake 3.18.1. 

Here is want I got:
```
$ export FC=ifort CC=icc
$ cmake -B _build_intel -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/beegfs/software/apps/crest-2.11/
$ make -C _build_intel
$ make -C _build_intel install 
make: Entering directory `/root/setup/ms/crest-2.11/_build_intel'
make[1]: Entering directory `/root/setup/ms/crest-2.11/_build_intel'
make[2]: Entering directory `/root/setup/ms/crest-2.11/_build_intel'
make[2]: Leaving directory `/root/setup/ms/crest-2.11/_build_intel'
[100%] Built target crest-exe
make[1]: Leaving directory `/root/setup/ms/crest-2.11/_build_intel'
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /mechthild/software/apps/crest-2.11/bin/crest
CMake Error at cmake_install.cmake:72 (file):
  file INSTALL cannot find
  "/root/setup/ms/crest-2.11/combi-scripts/crest_combi": No such file or
  directory.
```

Is it same to remove the crest_combi install instruction from the CMakeLists.txt file?

**Comment by pprcht** [comment]
Yes, remove the crest_combi instruction. In the current version it should even already be commented out in CMakeLists.txt, are you using an older commit?

**Comment by grisuthedragon** [comment]
I use the 2.11 source from the release page.

**Comment by pprcht** [comment]
Hm, thats weird. In the  [CMakeLists.txt of the main branch](https://github.com/grimme-lab/crest/blob/master/CMakeLists.txt) it is commented out (line 77-81). Maybe I will remove it entirely and update the release. Thanks for pointing this out.
