### ISSUE TITLE
unable to read crest_dynamics.trj

### ISSUE THREAD

**Issue by Artaious** [crest-lab/crest#362]
I'm making my first steps with crest, mainly following the firsts examples in the documentation webpage. 
I start by getting the alanineglycine geomtry from the there (https://crest-lab.github.io/crest-docs/page/examples/example_1.html) and running crest in the terminal by **crest struc.xyz --gfn2 --gbsa h2o -T 4**

After crest terminates normaly, I would like to visualize the dynamics within the **crest_dynamics.trj**. My issue is that neither with vmd nor with pymol I'm able to do so, getting an error when trying to load the trj file. 

Pymol proecedure: 
**load struc.xyz**

and then:
**load_traj crest_dynamics.trj** 

Which gives the following error --> ObjMolLoadTRJFile-Error: Failed to read expected coordinate value.
  This traj. does not match the loaded parameter/topology file.
  Likely cause: either the atom count or the periodic box settings
  are inconsistent between the two files.
-----------

[crest_dynamics.txt](https://github.com/user-attachments/files/17361447/crest_dynamics.txt)
[struc.txt](https://github.com/user-attachments/files/17361468/struc.txt)
(change the termination of the file to make possible its upload).

Anyhelp or comment will be greatly appreciated! 
Greetings.

**Comment by pprcht** [comment]
The file ending `.trj` is likely preoccupied in most visualization programs, we are keeping it around due to legacy purposes, which is a bit unfortunate, but the file is really just a plain `.xyz`.
In other words, if you rename the file to `crest_dynamics.trj.xyz` you should be able to open it just fine.

**Comment by Artaious** [comment]
> The file ending `.trj` is likely preoccupied in most visualization programs, we are keeping it around due to legacy purposes, which is a bit unfortunate, but the file is really just a plain `.xyz`. In other words, if you rename the file to `crest_dynamics.trj.xyz` you should be able to open it just fine.

Hello everyone, 
Sorry for the delay. I wanted to do a few trials before ansewring. 
It works as you said. Just by changing the name and using the trial version of ChemCraft I was able to visualise the dynamics and get what I needed. 

Thank you very much for your prompt reply. 
Regards.

**Comment by pprcht** [comment]
thanks for confirming!
