### ISSUE TITLE
QCG xyz outputfile

### ISSUE THREAD

**Issue by Exlonk** [crest-lab/crest#370]
HI there, I hope you are great, this is a silly question, the xyz outpufile of the qcg procedure is in angstroms or bohr?

**Comment by amabilee** [comment]
The xyz output file of the qcg procedure typically provides the coordinates in angstroms. This is the standard unit for most quantum chemistry software when it comes to outputting Cartesian coordinates.

**Comment by pprcht** [comment]
@amabilee is correct.
