### ISSUE TITLE
Does CREST 3.0.2 support gfn2//gfnff method ?

### ISSUE THREAD

**Issue by ElioChen** [crest-lab/crest#372]
**Describe the issue**
It seems like CREST/2.10.2 support gfn2//gfnff method. But it's hard to install a old version. Will new CREST versions support gfn2//gfnff method ?

**Comment by pprcht** [comment]
Yes it does still exist without reverting to an old version. If you want to use the original implementation, switch to it with `--legacy`.

If you instead wish to use the new calculator structure, you can simulate a similar setup via the `.toml` input files (no automated command here, sorry). 
But the jobs can be very customized this way. For example this one: https://crest-lab.github.io/crest-docs/page/documentation/inputfiles_examples.html#conformational-sampling-custom which runs the MDs/MTDs at GFN-FF and optimization at GFN2.
Even more levels of theory are possible:
```
#This is a CREST input file
input = 'struc.xyz'
runtype='imtd-gc'
#parallelization
threads = 8

#calculation data
[calculation]
[[calculation.level]]
method = "gfnff"

[[calculation.level]]
method ='gfn0'

[[calculation.level]]
method = 'gfn2'
refine='sp'

#molecular dynamics data
[dynamics]
#selecting the first [[calculation.level]] for dynamics, 
#it will be deactivated anywhere else
active = [1]
```

What you want for gfn2//gfnff is to define a `[[calculation.level]]` for gfnff and gfn2, and set `refine='sp'` for the latter. Don't bother with the [dynamics] / active setting.
