### ISSUE TITLE
[support] Parallelization and speedup options for medium-large systems

### ISSUE THREAD

**Issue by msh-yi** [crest-lab/crest#38]
I'm currently working on a organometallic system (170 atoms, 7 heavy non-metals, 3 metals) at the GFN2-xTB level. The CREST runs even with `squick` take a long time, and I find myself running up against the 1-week limit on my compute cluster. I have two questions about speeding up computations:

1. I've been trying to increase the memory and number of cores, and I noticed when going up to 30 cores and 30 GB/core (`OMP_STACKSIZE="30000m"`, `OMP_NUM_THREADS="30"`) that the output still shows `Estimated runtime for a batch of 6 MTDs on 4 threads`. Even if one MTD can only be run on one thread, shouldn't CREST be using at least 6 threads? Or is CREST using bundles of 7 threads for each MTD?
2. I have had good experiences with GFN-FF with other systems in the past, both with speed and quality, but the geometries just don't look reasonable in this case - are there any recommended settings to explore?

Thanks very much!

-Marcus

**Comment by pprcht** [comment]
Hi Marcus,
The threads for the MTDs _should_  be allocated in bundles, e.g., if the program has double the amount of threads available than it has MTDs to run, each MTD will be run using 2 threads, and so on.
However, I think in your case the program does not correctly use the 30 threads. It could be that the `OMP_STACKSIZE` and `OMP_NUM_THREADS` variables must not be allocated as a string, but we also had some issues with reading these parameters recently in general. Try using the `--T` option to tell `crest` the available number of threads, that will work.

Regarding the geometries we usually recommend adding some constraints to the calculation, but this of only makes sense if there are some specific angles or bond lengths that are responsible for the mismatch. In your case maybe the metal coordination spheres. This is usually very system specific and its hard to give general recommendations. @sespic might have some ideas.
