### ISSUE TITLE
ewin doesn't seem to be working

### ISSUE THREAD

**Issue by youcaizhu** [crest-lab/crest#384]
When I use a different ewin in version 3.0.2 they all come up with the same results and ewin doesn't seem to do anything!
Here are the different toml input files
1. ewin =100
# This is a CREST input file
runtype='ancopt'
input='L5.xyz'

# calculation level
[[calculation.level]]
method="gfn2"
chrg=1
UHF=3
alpb='toluene'

[[calculation.constraint]]
type = 'bond'
atoms=[[1,2],[1,4],[2,3],[3,4]]
fc=0.5

[cregen]
ewin = 100.00

2. ewin = 5
# This is a CREST input file
runtype='ancopt'
input='L5.xyz'

# calculation level
[[calculation.level]]
method="gfn2"
chrg=1
UHF=3
alpb='toluene'

[[calculation.constraint]]
type = 'bond'
atoms=[[1,2],[1,4],[2,3],[3,4]]
fc=0.5

[cregen]
ewin = 5.0

Both generate the exact same crestopt file, the below is the crestopt.log:

 52
 Etot=         -74.6582237684
 Cr        -0.0318306837       -1.2097890472       -0.9797505480
 P         -1.2403306837       -0.0511890472       -0.1178505480
 N          0.0259693163        0.6156109528        0.8952494520
 P          1.3336693163       -0.2205890472        0.0887494520
 C          2.2316693163       -1.2381890472        1.2520494520
 C          3.3231693163       -1.9762890472        0.8432494520
 C          4.0167693163       -2.7653890472        1.7533494520
 C          3.6546693163       -2.8463890472        3.0795494520
 C          2.5631693163       -2.1078890472        3.4868494520
 C          1.8756693163       -1.3250890472        2.5824494520
 C          2.3674693163        0.8195109528       -0.9216505480
 C          3.3955693163        1.5289109528       -0.3426505480
 C          4.2286693163        2.3556109528       -1.1008505480
 C          4.0247693163        2.4675109528       -2.4471505480
 C          3.0097693163        1.7738109528       -3.0507505480
 C          2.1835693163        0.9500109528       -2.2795505480
 C          0.1678693163        2.0362109528        0.8537494520
 C         -2.5175306837       -0.8912890472        0.8442494520
 C         -2.2479306837       -1.4495890472        2.0733494520
 C         -3.2748306837       -2.0810890472        2.7612494520
 C         -4.5493306837       -2.1575890472        2.2384494520
 C         -4.8332306837       -1.6012890472        1.0058494520
 C         -3.7998306837       -0.9774890472        0.3361494520
 C         -2.0119306837        1.2705109528       -1.0474505480
 C         -1.7073306837        1.5480109528       -2.3473505480
 C         -2.3546306837        2.5875109528       -2.9826505480
 C         -3.3091306837        3.3495109528       -2.3114505480
 C         -3.6224306837        3.0775109528       -1.0023505480
 C         -2.9576306837        2.0283109528       -0.3881505480
 H          3.6200693163       -1.9232890472       -0.1950505480
 H          4.8642693163       -3.3210890472        1.3727494520
 H          4.2164693163       -3.4757890472        3.7807494520
 H          2.2892693163       -2.1799890472        4.5292494520
 H          1.0267693163       -0.7591890472        2.9295494520
 H          3.6018693163        1.4784109528        0.7129494520
 H          5.0357693163        2.9135109528       -0.6518505480
 H          4.6430693163        3.0986109528       -3.0954505480
 H          2.8147693163        1.8350109528       -4.1146505480
 H          1.3696693163        0.3852109528       -2.7221505480
 H         -0.2784306837        2.5517109528        1.7491494520
 H         -0.3301306837        2.4502109528       -0.0307505480
 H          1.2519693163        2.3020109528        0.7652494520
 H         -1.2452306837       -1.3831890472        2.4724494520
 H         -3.0185306837       -2.5135890472        3.7381494520
 H         -5.3043306837       -2.6634890472        2.8251494520
 H         -5.8388306837       -1.6701890472        0.6099494520
 H         -4.0436306837       -0.5459890472       -0.6321505480
 H         -0.9755306837        0.9639109528       -2.8619505480
 H         -2.1581306837        2.8544109528       -4.0044505480
 H         -3.8318306837        4.1711109528       -2.7871505480
 H         -4.3684306837        3.6662109528       -0.4635505480
 H         -3.2244306837        1.8337109528        0.6491494520
  52
 Etot=         -74.7640857768
 Cr         0.0154907610       -1.4289961319       -1.1658618135
 P         -1.2917464249       -0.0138290930       -0.0828124866
 N          0.0341263268        0.6268472106        0.8972240636
 P          1.3518661805       -0.2195339342        0.1019973105
 C          2.2544049604       -1.2159919197        1.2750345492
 C          3.3311330331       -1.9767536033        0.8428004947
 C          4.0219630437       -2.7714528965        1.7432593186
 C          3.6568904309       -2.8473382956        3.0749746652
 C          2.5600521426       -2.1130486936        3.4932008815
 C          1.8697120377       -1.3205700142        2.5998536066
 C          2.3814952522        0.8373489182       -0.9116272332
 C          3.4160300774        1.5441094687       -0.3341561595
 C          4.2360740893        2.3599256915       -1.0990620668
 C          4.0248457680        2.4694688350       -2.4556704095
 C          2.9990855857        1.7651418159       -3.0531253894
 C          2.1806860646        0.9494327045       -2.2810633668
 C          0.1722397434        2.0593747395        0.8625096247
 C         -2.5421986544       -0.8608778103        0.8673840456
 C         -2.2499409759       -1.4510232210        2.0817602390
 C         -3.2674265129       -2.0885395048        2.7691777266
 C         -4.5473173154       -2.1618899875        2.2470970282
 C         -4.8327112507       -1.6086855869        1.0090207564
 C         -3.8142554031       -0.9741037610        0.3297067727
 C         -2.0309933548        1.2926081278       -1.0317808519
 C         -1.7127359141        1.5549840018       -2.3498878536
 C         -2.3598517030        2.5948342353       -2.9874015971
 C         -3.3121235333        3.3546086867       -2.3154075124
 C         -3.6289206335        3.0832867291       -1.0004518827
 C         -2.9765662377        2.0452516966       -0.3725925093
 H          3.6256892316       -1.9239489878       -0.1971062787
 H          4.8692401755       -3.3255242713        1.3716864163
 H          4.2134568781       -3.4698676815        3.7731127145
 H          2.2823612392       -2.1764860857        4.5325399299
 H          1.0207991218       -0.7515140491        2.9371934568
 H          3.6067585579        1.4780303618        0.7234779174
 H          5.0393108723        2.9150773618       -0.6466376224
 H          4.6435892076        3.0981853562       -3.0900966558
 H          2.8130897568        1.8331963823       -4.1147313893
 H          1.3677089892        0.3820838181       -2.7256233732
 H         -0.2716968950        2.5491765070        1.7481522815
 H         -0.3258717804        2.4619336145       -0.0265802118
 H          1.2429127468        2.3117048054        0.7785179589
 H         -1.2460212620       -1.3828017108        2.4760758320
 H         -3.0240008423       -2.5152970950        3.7376498034
 H         -5.3079651540       -2.6634068856        2.8258565442
 H         -5.8351536518       -1.6700812761        0.6093997867
 H         -4.0432913804       -0.5414338702       -0.6367407719
 H         -0.9734793357        0.9609374454       -2.8641855245
 H         -2.1538064686        2.8520553644       -4.0108519524
 H         -3.8283561851        4.1716789640       -2.7963890303
 H         -4.3678307715        3.6667172708       -0.4662600623
 H         -3.2257461874        1.8326657996        0.6577117831
  52
 Etot=         -74.7898915777
 Cr         0.0050472285       -1.5262246979       -1.2541005341
 P         -1.2839670132       -0.0890076948       -0.1576912444
 N          0.0422395028        0.5916322774        0.8192916432
 P          1.3400798530       -0.2991461896        0.0339918807
 C          2.2896353132       -1.1712580054        1.2951095021
 C          3.3523160568       -1.9570039787        0.8483691433
 C          4.0304026146       -2.7718918218        1.7351573819
 C          3.6534425550       -2.8433376252        3.0671450529
 C          2.5556440995       -2.1101657542        3.4985128781
 C          1.8736449360       -1.2912270849        2.6185867789
 C          2.3920830742        0.8407947280       -0.9010622342
 C          3.4328610398        1.5546730807       -0.3174405478
 C          4.2452041798        2.3660016401       -1.0936378492
 C          4.0233204276        2.4705240682       -2.4557264236
 C          2.9896041583        1.7602321934       -3.0475936617
 C          2.1792084925        0.9489326805       -2.2739669557
 C          0.1751991023        2.0512435246        0.8574697744
 C         -2.5606751458       -0.8059133470        0.8893757893
 C         -2.2561488669       -1.4269354458        2.0966773771
 C         -3.2601698981       -2.0926308066        2.7792925197
 C         -4.5426324690       -2.1686771473        2.2582801326
 C         -4.8292110859       -1.6144694564        1.0182703992
 C         -3.8306578860       -0.9502122307        0.3342567240
 C         -2.0446749826        1.2919174581       -1.0199157062
 C         -1.7247096400        1.5635238477       -2.3450710258
 C         -2.3665093191        2.6046859078       -2.9874812748
 C         -3.3185020727        3.3644198181       -2.3182867161
 C         -3.6372584029        3.0941970208       -0.9974373254
 C         -2.9922894095        2.0573817965       -0.3513395103
 H          3.6405498956       -1.9158076110       -0.1952738612
 H          4.8734875561       -3.3394756571        1.3706118761
 H          4.2066383197       -3.4626656834        3.7603644342
 H          2.2643191214       -2.1766979994        4.5352859961
 H          1.0173537768       -0.7256715785        2.9527335688
 H          3.6205360426        1.4747722457        0.7437187151
 H          5.0505991928        2.9201081680       -0.6403260432
 H          4.6449740185        3.0981013657       -3.0800068162
 H          2.8102955466        1.8286064840       -4.1102142743
 H          1.3719292886        0.3700380120       -2.7221007830
 H         -0.2674226945        2.5017880063        1.7545294557
 H         -0.3043240895        2.5092282366       -0.0148155072
 H          1.2326191732        2.3325481785        0.8246307467
 H         -1.2490157926       -1.3714442653        2.4843494008
 H         -3.0284865152       -2.5294694499        3.7404259866
 H         -5.3112402392       -2.6662321505        2.8301213607
 H         -5.8267201717       -1.6830634155        0.6107748977
 H         -4.0500799073       -0.5286198042       -0.6392189732
 H         -0.9860506670        0.9605424692       -2.8608869165
 H         -2.1484853822        2.8466214751       -4.0159262392
 H         -3.8251426482        4.1770997657       -2.8153553588
 H         -4.3755999846        3.6791272204       -0.4720271607
 H         -3.2322558360        1.8361767779        0.6798410296
.......
  52
 Etot=         -74.8262040403
 Cr        -0.1213355719       -1.8934818958       -1.9061954485
 P         -1.4650901943       -0.6941048434       -0.4735072688
 N         -0.0863602364       -0.4301635324        0.5479932626
 P          1.3063273408       -0.9730387812       -0.3554095976
 C          2.4535280933       -1.3985926600        0.9911705396
 C          3.8156010086       -1.1291535821        0.8845343366
 C          4.6787353028       -1.5411515163        1.8844961320
 C          4.1930935696       -2.2358990675        2.9815096016
 C          2.8412720773       -2.5320313930        3.0755861561
 C          1.9741690330       -2.1272475882        2.0780326893
 C          1.9573037225        0.5813985396       -1.0566478189
 C          2.4438320301        1.6383540933       -0.2935495428
 C          2.7588303208        2.8388428843       -0.9078355324
 C          2.6030846185        2.9873496193       -2.2765331970
 C          2.1438961991        1.9282179970       -3.0459369840
 C          1.8190776767        0.7331428589       -2.4338134334
 C         -0.0311796775        0.5697871166        1.6092819934
 C         -2.7934763431       -0.8623977015        0.7588428275
 C         -2.5713733375       -1.6537357203        1.8841662008
 C         -3.5898251745       -1.8611414016        2.7955625857
 C         -4.8404774793       -1.3028222009        2.5765748141
 C         -5.0745678458       -0.5435466233        1.4405597415
 C         -4.0583234685       -0.3284274354        0.5264172370
 C         -1.7334992683        0.9456425150       -1.2310854768
 C         -1.4607095332        1.0397377951       -2.5931517687
 C         -1.4917676882        2.2631467022       -3.2340833157
 C         -1.7879493332        3.4074682740       -2.5077882897
 C         -2.0758497045        3.3199726999       -1.1553418659
 C         -2.0565707966        2.0930266144       -0.5134473074
 H          4.1941418792       -0.5930346764        0.0245276272
 H          5.7336190368       -1.3224095208        1.8075317969
 H          4.8702834646       -2.5536236236        3.7602859095
 H          2.4680375249       -3.0839473102        3.9256263191
 H          0.9203425518       -2.3621821435        2.1351757827
 H          2.5862571447        1.5184833299        0.7708482261
 H          3.1285783214        3.6625783713       -0.3152587513
 H          2.8485040091        3.9273267942       -2.7474848263
 H          2.0420528485        2.0405049501       -4.1148364812
 H          1.4587744893       -0.1187943813       -3.0198774727
 H         -0.9538087070        0.5273381529        2.1883247485
 H          0.0937870465        1.5787941364        1.2072699206
 H          0.8048273213        0.3422730824        2.2708984314
 H         -1.5955170555       -2.0926475755        2.0393369686
 H         -3.4141428046       -2.4621950239        3.6755363629
 H         -5.6360511337       -1.4662024591        3.2882046032
 H         -6.0528585463       -0.1204057773        1.2659917722
 H         -4.2413104346        0.2585777327       -0.3636440240
 H         -1.2334474669        0.1213876507       -3.1453228801
 H         -1.2871010811        2.3317929523       -4.2919040918
 H         -1.8031146278        4.3680050868       -3.0004454703
 H         -2.3179883551        4.2123438917       -0.5972697031
 H         -2.3032563193        2.0245541394        0.5363554649

Meanwhile, the structure of the first one differs from the last one by more than 100kal/mol, and if I understand Etot= -74.8262040403 correctly the unit is hartree. So I want to select only conformations within 5kcal/mol of the lowest energy out of all the optimized structures, what should I do? Thank you very much for your answer.

**Comment by pprcht** [comment]
`runtype='ancopt'` performs a geometry optimization, no conformational sampling.This has ***nothing*** to do with `ewin` and hence is unaffected by the setting.  `crestopt.log` is the optimization trajectory, not an ensemble, i.e., it shows how the structure changes upon optimization.

**Comment by youcaizhu** [comment]
Thank you for your answer. If I want to do the generation of the set of conformations first and subsequently optimize these conformations. The optimization is done according to gfn2-xtb, and the optimization results in retaining only conformations up to 5kcal/mol, do you have any better suggestion to use crets3.

**Comment by pprcht** [comment]
Set `runtype="imtd-gc"`
