### ISSUE TITLE
searches are slower in 2.11 than in 2.10.2

### ISSUE THREAD

**Issue by ucb-mgcf** [crest-lab/crest#39]
Hello,

In every case I've examined, I'm getting longer computation times for crest 2.11 runs versus 2.10.2.  I've simplified things by focusing on a small example for testing purposes, with initial geometry:

```
23

  O   -2.4826000    0.0073000    0.1112000
  O    2.4266000   -1.9214000    1.5577000
  O    0.4724000   -2.2815000    2.1394000
  N   -0.5988000   -0.9313000    0.0784000
  N   -1.2670000    2.2601000    1.2896000
  C    0.7790000   -1.1909000    0.0675000
  C   -0.7769000    1.5531000    0.0983000
  C   -1.2718000    0.1806000    0.0953000
  C    1.0879000   -2.0511000   -1.1809000
  C   -1.1674000    2.3432000   -1.1707000
  C    1.2311000   -1.8237000    1.2990000
  H    1.3752000   -0.2848000   -0.0509000
  H    0.3093000    1.6049000    0.1603000
  H   -1.1261000   -1.7060000    0.0663000
  H    0.8079000   -1.5128000   -2.0900000
  H    0.5372000   -2.9945000   -1.1577000
  H    2.1546000   -2.2753000   -1.2487000
  H   -0.8189000    1.8310000   -2.0703000
  H   -0.7083000    3.3341000   -1.1509000
  H   -2.2499000    2.4704000   -1.2356000
  H   -0.8858000    1.7848000    2.1104000
  H   -0.8626000    3.1991000    1.2712000
  H    3.0351000   -1.5952000    1.0111000
```

This takes around 9 min in 2.10.2 and 18 min in 2.11.  I've noticed that more structures in each iteration, and sometimes more MTD iterations, etc. are used in 2.11.  Here's some associated output:

```
2.10.2:
 515 structures remain within    12.00 kcal/mol window
 57 structures remain within     6.00 kcal/mol window
 510 structures remain within    12.00 kcal/mol window
 159 structures remain within     6.00 kcal/mol window
 199 structures remain within     6.00 kcal/mol window
 206 structures remain within     6.00 kcal/mol window
conformer energy window  /kcal :    6.00
 # in E window                206
 62 structures remain within    10.00 kcal/mol window
 212 structures remain within     6.00 kcal/mol window
 conformer energy window  /kcal :   6.0000
```

```
2.11:
 655 structures remain within    12.00 kcal/mol window
 31 structures remain within     6.00 kcal/mol window
 Increasing energy window to include more...
 157 structures remain within     9.00 kcal/mol window
 550 structures remain within    12.00 kcal/mol window
 42 structures remain within     6.00 kcal/mol window
 676 structures remain within    12.00 kcal/mol window
 186 structures remain within     6.00 kcal/mol window
 672 structures remain within    12.00 kcal/mol window
 166 structures remain within     6.00 kcal/mol window
 678 structures remain within    12.00 kcal/mol window
 163 structures remain within     6.00 kcal/mol window
 401 structures remain within     6.00 kcal/mol window
 411 structures remain within     6.00 kcal/mol window
conformer energy window  /kcal :    6.00
 # in E window                411
 28 structures remain within    10.00 kcal/mol window
 386 structures remain within     6.00 kcal/mol window
 conformer energy window  /kcal :   6.0000
```

Is it possible for me to use keywords to change the defaults so as to get times more similar to what 2.10.2 produces?

I noticed in the release notes for the development version of 2.11: "Defaults for ensemble sorting thresholds have been changed slightly (ethr = 0.05 kcal/mol, was 0.1 kcal/mol; bthr = 1%, was 15.0 MHz)".  Accordingly, I tried ethr values of 0.1 and 0.11, and this seems to decrease the times somewhat, but both cases result eventually in "no convergence in svdcmp".  I also tried using --v2i, and this finishes in 7 min, but produces only 4 conformers, compared to 45 for 2.10.2 and 80 for default 2.11.

thanks

**Comment by pprcht** [comment]
Sounds to me as if the MTDs run more stably and produce more structures withing the same energy window compared to the previous version of the program. Fully optimizing a  larger number of structures requires more computation time, this shouldn't surprise all that much. In fact, at the end there were 411 structures to fully optimize compared to previously 206, that is consistent with the 9 to 18 min difference you mentioned.
This probably is also a result of the changed sorting parameters as you have observed, but we generally wouldn't recommend to go back to the old settings. The old sorting can still be used with the setting `--oldcr`. This is a legacy option and should be used with caution.
`--v2i` _is_ the default for both 2.10.2 and 2.11, no idea why there were should be runtime differences.

If speed is the main concern for you project, have you tried GFN-FF? This should be faster almost by an entire order of magnitude.

**Comment by ucb-mgcf** [comment]
Thanks for the reply.  I concur that the new version is searching more thoroughly, and in fact it produces a superior result energetically for this molecule.  While this capability is certainly welcome, I'm just wondering what the best set of options to use is for the case in which we want to benefit from crest's ability to alter the covalent structure of the molecule, but only have the resources to run a search that finishes in a timeframe similar to that of 2.10.2, while of course accepting that the result may be a slightly less optimal ensemble.  Please let me know your recommendation for this.  Are there alternatives to using the full --oldcr, such as changing only 1 or 2 of the parameters this implies?  Do you suggest lowering --ewin a little?

**Comment by fabothch** [comment]
If computational cost is the limiting factor, then perhaps searching on a lower level potential energy surface (PES) by employing the GFN-FF force field is the way to go. You gain the speed of the underlying force field and do not have to adjust the search parameters.

**Comment by ucb-mgcf** [comment]
Hello,

I happened to try switching OMP_NUM_THREADS from **16,1** to **1,16**, and I noticed that this appears to significantly speed up crest simulations on the cluster I'm using, and indeed the new times appear to be similar to what I was previously getting with version 2.10.2 (for which I was using 16,1).  Is this expected, and do you recommend that I switch in general to this modality, i.e. using OMP_NUM_THREADS=1,n?

thanks

**Comment by pprcht** [comment]
The automatic reading of parallelization variables from OMP_NUM_THREADS seems to be a bit broken currently, as discussed in #38. 
To be sure the right number of threads is taken best use the `--T <threads>` command line argument. 
If OMP_NUM_THREADS=1,n works on your system you may use this also.

**Comment by ucb-mgcf** [comment]
I was using -T 16 in both cases.  I also tested -T 16 with OMP_NUM_THREADS=1,1 and this gives a time intermediate between the 2 others.  So my 3 timings are (again, all 3 used -T 16):

OMP_NUM_THREADS=1,1:     5h :56m
OMP_NUM_THREADS=1,16:   3h :38m
OMP_NUM_THREADS=16,1:   7h :36m

Is the 1,16 job then actually using more than 16 effective core, or rather, more than 16 threads?  Also, I should mention that all three cases used MKL_NUM_THREADS=16.   Is this ok?  Is it preferable to omit the OMP_NUM_THREADS altogether?

Thanks

**Comment by awvwgk** [comment]
One thing to keep in mind with [`OMP_NUM_THREADS`](https://www.openmp.org/spec-html/5.0/openmpse50.html) is that the last value is implicitly repeated for all deeper levels, so `1,16` allows 16 threads in the second layer that can each spawn 16 threads. There is [`OMP_MAX_ACTIVE_LEVELS`](https://www.openmp.org/spec-html/5.0/openmpse56.html) influencing how deep OMP regions can be nested.

**Comment by ucb-mgcf** [comment]
In all examples, I'm using OMP_MAX_ACTIVE_LEVELS=1.  Unless I'm misunderstanding, this would seem to nullify the distinction between say 1,16 and 1,1, however I do observe timing differences for these.  Or is it that this is only for _active_ levels, which might allow for some variation?  Please advise on what options for these variables you would recommend.  I'm mainly trying to use the best general options in automated scripts, which are used to initiate crest and xtb calculations for numerous users at our computational facility.

**Comment by awvwgk** [comment]
Keep in mind that the `OMP_MAX_ACTIVE_LEVELS` works on per process basis, `xtb` is invoked as subprocess from `crest` and can therefore still run threaded.
