### ISSUE TITLE
Unusal error after version upgrade

### ISSUE THREAD

**Issue by jungsdao** [crest-lab/crest#40]
Hello, thank you for developing and sharing fantastic code :)
I've enjoyed using CREST since the previous version, but after recent release and upgrade, I'm facing the unseen errors. 
I'm trying with `-nci` for molecular fragments. 
The command line input for this work is as follows. 
`crest mixture.xyz --nofeftopo -g Acetone -nci -T 8 > stdout.log`

However after running it is terminated within a few seconds with following error message. 
I think I didn't encounter such message in previous version, therefore I suspect it might be related to somewhat with version upgrade. 
I would be greatly thankful if you could give any comment or advice to circumvent this issue. 
Many thanks in advance. 

Best regards, 
Hyunwook  

[crest_error.zip](https://github.com/grimme-lab/crest/files/6146971/crest_error.zip)

 Command line input:
 > crest mixture.xyz --nofeftopo -g Acetone -nci -T 8

  --gbsa Acetone : implicit solvation
  -nci  : Special NCI mode for non-covalently bound complexes or clusters.
  -T 8 (CPUs/Threads selected)
  Automatically generated ellipsoide potential for NCI mode:
> $wall
>   potential=polynomial
>   ellipsoid: 21.53932170950744, 18.23314152477000, 17.26536115887853, all
 
 
 -------------------------
 xTB Geometry Optimization
 -------------------------
 Geometry successfully optimized.
 WARNING! Change in topology detected!
 The topology change was seen in the initial geometry optimization.
 This could be an artifact of the chosen theory level (--gfn2).
 You can check the optimization trajectory in the "xtbopt.log" file.
 Try either of these options:

    A) Pre-optimize your input seperately with xtb and use the optimized
       structure as input for CREST. (Only recommended if structure is intact)

    B) Restart the same CREST call as before, but ignore the topology change
       by using the "--noreftopo" keyword. (May produce artifacts)

    C) Fix the initial input geometry by introducing bond length constraints
       or by using a method with fixed topology (GFN-FF).

**Comment by pprcht** [comment]
You wrote `--nofeftopo`, it should  be `--noreftopo`
Otherwise the warning message is pretty clear, have you tried the suggested things? For NCI searches it also might be appropriate to turn of all topology checks with `--notopo`

**Comment by yanfeiguan** [comment]
Hi, thank you for developing this awesome tool. I am also facing the same issue for 2.11.
The command I am using is:

`crest -gfn2 -xnam xtb -chrg -1 -g methanol -nozs -ewin 3.0 -T 20 -cinp control`

It randomly raises the error of "Change in topology detected!" (By "randomly" I meant for the exactly two runs with the same input in the same directory, one raised such error, while the second run might success)

The same command works for 2.10.

**Comment by pprcht** [comment]
Again, this is not really an error but a warning (which gives you several options to treat it). The topology detection is deterministic for the same input, but  it is not necessarily deterministic for geometry optimizations (e.g. if it oscillates without smooth convergence for some reason). This could for example be an effect of the defined constraints in your `control` file.

So, to avoid the warning pre-optimize the input structure with `xtb` OR tell `crest` to ignore this check with `--noreftopo`. This warning exists to avoid wasting calculation times on systems that might have problems already in a regular `xtb` calculation and if it is present it might be worthwhile to investigate that.

**Comment by jungsdao** [comment]
Thank you for your comment, I made a silly mistake.
