### ISSUE TITLE
MTD convergence error

### ISSUE THREAD

**Issue by jungsdao** [crest-lab/crest#42]
Hello, While setting initial parameters for MTD, I encounter MTD convergence issue in some systems.
It seems slight modification remedies this issue, but for some case, I constantly get this error message.
If there's any suggested solution to this problem, I'll be very happy to have it!
Many thanks in advance.

Best regards, 
Hyunwook 

-------------------------------------
Starting a trial MTD to test settings
-------------------------------------
 Trial MTD 1 did not converge!
 Reducing the time step to 4 fs and trying again...

 Trial MTD 2 did not converge!
 Reducing the time step to 3 fs and trying again...

 Trial MTD 3 did not converge!
 Reducing the time step to 2 fs and trying again...

 Trial MTD 4 did not converge!
 Reducing the time step to 1 fs and trying again...

 Trial MTD 5 did not converge!
 Time step can`t be reduced further!
 Trying to turn SHAKE off...

 Trial MTD 6 did not converge!
 Automatic xtb restart failed 6 times!
 Please try other settings by hand.

[question.zip](https://github.com/grimme-lab/crest/files/6304014/question.zip)

**Comment by pprcht** [comment]
The wall potential  form `-nci` seems to interfere with the calculation. Either don't use this flag or make the wall potential a bit larger (e.g. `-wscal 1.2`, for 20% larger ellipsoid axes).
