### ISSUE TITLE
Crest performance in Windows Subsystem for Linux/Ubuntu

### ISSUE THREAD

**Issue by pwging13** [crest-lab/crest#62]
I've been using crest in Ubuntu in the WSL in Windows 10 for almost a year without any issues.  I **_THINK_** a recent Windows Update has significantly slowed it down in the last week or so.  I think the Windows update is KB5003637.

I have a Fedora 33 box and a Windows 10 box, both running a Core i7-4770 or 4770s with 12 or 16 GB of ram with an SSD, and historically, the performance in WSL has been highly comparable between the two.

Has anyone else that runs crest/xtb within WSL observed this in the last couple weeks?

**Comment by meghnashankar** [comment]
I just started using crest a couple days ago, but I've got a Core i7-8565U on my PC with 16 GB RAM and it takes me 25 minutes to run `crest molecule.xyz` on a molecule with 23 atoms (from here https://github.com/grimme-lab/crest/issues/39). I'm using WSL with Ubuntu 20.04 on Windows 10 (Version 10.0.19043 Build 19043).
I can't speak for whether it is slower than before but this might give some idea for how much time it takes others.

**Comment by pwging13** [comment]
That's slow. I've been using it in WSL for a while and sometime in the last
month or two something changed in Windows/WSL and it runs super slow
compared to before. I have some pretty identical machines, one running
Fedora 33 and one running windows 10/WSL, and they used to run at the same
speed more or less. Now not so much.

**Comment by meghnashankar** [comment]
Interesting. Out of curiosity, do you have a ballpark for how long it would take to run 80 atoms on the same machine?
