### ISSUE TITLE
Crest performance on Ubuntu virtual machine in Azure

### ISSUE THREAD

**Issue by meghnashankar** [crest-lab/crest#68]
Hi, I am a student new to Crest, and I am trying to find conformers for molecules that range from 80-300 atoms. I initially tried to run crest through WSL Ubuntu 20.04 on my laptop, but then I discovered that since my laptop only has 4 cores, it is not able to run Crest on even the 80 atom molecules in a reasonable amount of time. Just to experiment, I bought an Ubuntu 20.04 VM on Azure with 48 cores. I've been trying to run a test 80 atom molecule on that, but since I ssh into the VM, occasionally my connection will be reset and crest appears to stop running. After I ssh back in, I run `ps` and crest is not shown to be running, and there are no files `crest_conformers.xyz` etc. I would hope that crest would continue to run even when I am not connected to the VM, but that doesn't appear to be the case. Is there no way around this?

Additionally, could anyone help me figure out an appropriate number of cores and amount of time for these optimizations to run? Right now I'm just running the command `crest molecule.xyz -T <number of threads>` but I would appreciate suggestions for other command line arguments that would be useful in this case. I'm trying to find the lowest energy conformational isomers so that I can run DFT calculations on them.

**Comment by myshevchuk** [comment]
Use a terminal multiplexer such as `screen` or `tmux`.
