### ISSUE TITLE
Way to change the collective variables in CREST MTD-entropy mode?

### ISSUE THREAD

**Issue by epunzal2** [crest-lab/crest#76]
From what I understand in the MTD-entropy mode, dihedral angles are used as the geometric descriptors to get bias and seed structures throughout the run. Is there a way to specify the atoms for this metric for collective variables? And, is there a way to change the metric? Thank you.

**Comment by pprcht** [comment]
Selecting only specific atoms for the RMSD bias is possible via the constraint file in the $metadyn block.
However, selecting specific atoms for the PCA clustering of the seed structures or choosing other metrics than the dihedral angles can currently only be done in the code and not be adjusted via commands.
