### ISSUE TITLE
forrtl: severe (124): Invalid command supplied to EXECUTE_COMMAND_LINE

### ISSUE THREAD

**Issue by jouteurestaque** [crest-lab/crest#79]
Hi
I have just set up XTB and CREST, and while I could make XTB run (single point calculation checked), with that simple crest command 
crest XTB233.xyz -g H2O
it failed and gave me that error
forrtl: severe (124): Invalid command supplied to EXECUTE_COMMAND_LINE
Image              PC                Routine            Line        Source             
crest              00000000027B31CD  Unknown               Unknown  Unknown
crest              0000000000616661  Unknown               Unknown  Unknown
crest              0000000000638C75  Unknown               Unknown  Unknown
crest              00000000004048D2  Unknown               Unknown  Unknown
crest              00000000029B3FB0  Unknown               Unknown  Unknown
crest              00000000004047B7  Unknown               Unknown  Unknown

and the out file end  up like that

 Command line input:
 > /nfs/home/galanoj/xtb/6.4.1/bin/crest-2.11.1/crest XTB23.xyz -g H2O

  --gbsa H2O : implicit solvation
 
 -------------------------
 xTB Geometry Optimization
 -------------------------

I am not sure what is happening?
If you guys got any hint?
cheers

**Comment by pprcht** [comment]
If this is something SLURM related I'm not sure we will be able to help.

Have you tried providing `crest` with the complete path to `xtb`?
I.e., something like
 `/path/to/your/crest XTB233.xyz -g h2o -xnam $xtbdir/bin/xtb `
