### ISSUE TITLE
SIGSEGV when using constraining file

### ISSUE THREAD

**Issue by sibo** [crest-lab/crest#87]
I am trying to run a constrained CREST search using .xcontrol.new, which constrains two specific atoms, and also constrains every bond. The crest output file always stops at the same point:

             Command line input:
             >  Command line input:
             > /hrc_stor/home/sxl374/_programs/xtb/bin/crest TSguess.xyz --chrg 1 --uhf 3 -nozs -cinp .xcontrol.new -T 24
            
              -cinp : .xcontrol.test
              -T 24 (CPUs/Threads selected)
             ".xcontrol.test" file present.
             content of the constraining file (sorted):
             <skipped due to length of constraining file>
             fix file: coord.ref
              atoms: 1-24,27-74
                 # of atoms considered for RMSDs:72
            
             -------------------------
             xTB Geometry Optimization
             -------------------------
             Geometry successfully optimized.

            ------------------------------------------------
            Generating MTD length from a flexibility measure
            ------------------------------------------------
             Calculating WBOs... done.

And the error "forrtl: severe (174): SIGSEGV, segmentation fault occurred" occurs. When I run the same calculation, but using a modified .xcontrol.test which removes ~27  of the bond constraints from .xcontrol.new, CREST does not crash. I am running with "ulimit s unlimited" and "export OMP_STACKSIZE=4G" with CREST v. 2.10.2

[crest_sigsegvFiles.zip](https://github.com/grimme-lab/crest/files/7685967/crest_sigsegvFiles.zip)

**Comment by pprcht** [comment]
Hi,
I'm not really sure whats the issue with this. It could be the dual constrain due to the reference file (`atoms:` and `reference=`) and the distances, maybe they interfere. Also, you specified two different force constants, but xtb, as far as I know, can only use one global force constant for all.
Just to rule out technical problems, have you tried using the newer program version 2.11+?
