### ISSUE TITLE
no convergence in svdcmp

### ISSUE THREAD

**Issue by pauplaterra** [crest-lab/crest#88]
Hello,

I sometimes find an error in the structure crossing part saying 'no convergence in svdcmp'. I would appreciate if there is some clues to avoid this error. 

Thank you

**Comment by pprcht** [comment]
Hi,
this is an error from the RMSD module's  structure alignment (code not written by us), I had not yet the time to implement a workaround.
Strangely, this error occurs mostly in the structure crossing step, despite the same RMSD routine being called on several other places in the code. My guess would therefore be that the structure crossing generates some really bad z-matrices that cause the problems with the svdcmp. For now, to avoid this issue try turning off the crossing with `--nocross`

**Comment by pprcht** [comment]
#89 should take care of it.
